export const PRODUCTS = [
  {
    id: 'G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY',
    name: 'Monkey D. Luffy',
    series: 'Four Emperors Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_000_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_7_jfergr.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_6_mhh8ob.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_8_zfxxvy.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_5_jykp1n.webp',
    ],
  },
  {
    id: 'G5STUDIOONEPIECETHEROADTOBEKING',
    name: 'Monkey D. Luffy',
    series: 'The Road To Be King',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 28_650_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOONEPIECETHEROADTOBEKING_10_wdq6my.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOONEPIECETHEROADTOBEKING_9_qs0kmp.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOONEPIECETHEROADTOBEKING_8_faltis.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOONEPIECETHEROADTOBEKING_6_ttkudp.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOONEPIECETHEROADTOBEKING_2_zdcxcx.webp',
    ],
  },
  {
    id: 'G5STUDIOONEPIECEENMAFORMRORONOAZORO',
    name: 'Roronoa Zoro',
    series: 'Enma Form',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_5_y3jy9u.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_4_agwrkz.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESLUFFY',
    name: 'Monkey D. Luffy',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 6_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESLUFFY_1_gyyxbk.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESLUFFY_2_foyzua.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESZORO',
    name: 'Roronoa Zoro',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESZORO_1_sfbppo.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESZORO_2_jcsc3h.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESNAMI',
    name: 'Nami',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESSERIESNAMI_1_a0o0l8.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESSERIESNAMI_4_zsscpc.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESUSOPP',
    name: 'Usopp',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESSERIESUSOPP_1_zdfmeg.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESSERIESUSOPP_4_wwzssy.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESSANJI',
    name: 'Vinsmoke Sanji',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESSANJI_1_bwouuo.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESSANJI_2_s2yeya.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESCHOPPER',
    name: 'Tony Tony Chopper',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_1_ss1ydb.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_2_nrtsby.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESROBIN',
    name: 'Nico Robin',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 6_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESROBIN_1_kisc1x.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESROBIN_4_yw59uy.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESFRANKY',
    name: 'Franky',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 6_100_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESFRANKY_1_ncnmtz.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESFRANKY_2_bq46jp.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESBROOK',
    name: 'Brook',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESBROOK_1_tz5gyd.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESBROOK_5_ce3n3p.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESJINBE',
    name: 'Jinbe',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESJINBE_1_d8ixa3.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESJINBE_3_ahmdwc.webp',
    ],
  },
  {
    id: 'G5STUDIOYAMATO',
    name: 'Yamato',
    series: '',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOYAMATO_1_xbejip.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOYAMATO_4_lvphta.webp',
    ],
  },
  {
    id: 'SURGESTUDIO_ITACHI',
    name: 'Uchiha Itachi',
    series: 'Uchiha Clan Susanoo Series',
    studio: 'Surge Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 3_800_000,
    images: ['https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_ITACHI_1_rlritg.jpg'],
  },
  {
    id: 'SURGESTUDIO_MADARA',
    name: 'Uchiha Madara',
    series: 'Uchiha Clan Susanoo Series',
    studio: 'Surge Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 3_800_000,
    images: ['https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_MADARA_1_txrcsq.jpg'],
  },
  {
    id: 'SURGESTUDIO_SASUKE',
    name: 'Uchiha Sasuke',
    series: 'Uchiha Clan Susanoo Series',
    studio: 'Surge Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 3_800_000,
    images: ['https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_SASUKE_1_k6ivfs.jpg'],
  },
  {
    id: 'SURGESTUDIO_KAKASHI',
    name: 'Hakate Kakashi',
    series: 'Uchiha Clan Susanoo Series',
    studio: 'Surge Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 3_800_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_KAKASHI_1_ifneav.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_KAKASHI_2_q4e5fi.jpg',
    ],
  },
  {
    id: 'SURGESTUDIO_OBITO',
    name: 'Uchiha Obito',
    series: 'Uchiha Clan Susanoo Series',
    studio: 'Surge Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 3_800_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_OBITO_1_m08ywr.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_OBITO_2_iwwu4l.jpg',
    ],
  },
  {
    id: 'SURGESTUDIO_SHISUI',
    name: 'Uchiha Shisui',
    series: 'Uchiha Clan Susanoo Series',
    studio: 'Surge Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 3_800_000,
    images: ['https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_SHISUI_1_fffcy9.jpg'],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOHOKAGESERIES1.HASHIRAMASENJU',
    name: 'Senju Hashirama',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_500_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOHOKAGESERIES1.HASHIRAMASENJU_5_uy2xfw.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOHOKAGESERIES1.HASHIRAMASENJU_1_ducidy.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES2.TOBIRAMASENJU',
    name: 'Senju Tobirama',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_500_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES2.TOBIRAMASENJU_4_wyka26.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES2.TOBIRAMASENJU_1_vmrare.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIOSARUTOBI',
    name: 'Sarutobi Hiruzen',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOSARUTOBI_1_kxxv5g.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOSARUTOBI_3_ktn9uo.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIOWCFHOKAGESERIES4.MINATONAMIKAZE',
    name: 'Namikaze Minato',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOWCFHOKAGESERIES4.MINATONAMIKAZE_3_kxk2tg.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOWCFHOKAGESERIES4.MINATONAMIKAZE_1_ufsq0m.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES5.TSUNADE',
    name: 'Senju Stunade',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES5.TSUNADE_4_btt0mp.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES5.TSUNADE_1_wos5ax.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES5.TSUNADE_2_hpf9kx.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIOHOKAGESERIESWCFKAKASHI',
    name: 'Hatake Kakashi',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 2_100_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOHOKAGESERIESWCFKAKASHI_3_smp1vj.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOHOKAGESERIESWCFKAKASHI_1_kfdykg.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOHOKAGESERIESWCFKAKASHI_4_unbb1t.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES7.NARUTO',
    name: 'Uzumaki Naruto',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 5_100_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES7.NARUTO_8_tjh8w3.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES7.NARUTO_1_c6gxmd.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES_HOKAGEROCK',
    name: 'Hokage Rock',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 6_100_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES_HOKAGEROCK_2_qtzwp9.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES_HOKAGEROCK_1_vhycvg.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIOJIRAIYA',
    name: 'Jiraiya',
    series: 'Sannin Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 2_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOJIRAIYA_1_avp9vm.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOJIRAIYA_5_qjjaxl.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOJIRAIYA_2_ihu5tf.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIOTSUNADE',
    name: 'Senju Stunade',
    series: 'Sannin Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_100_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOTSUNADE_1_ata85f.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOTSUNADE_2_dyww5r.webp',
    ],
  },
  {
    id: 'STONECUSTOM3SANNINOROCHIMARU',
    name: 'Orochimaru',
    series: 'Sannin Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 2_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOM3SANNINOROCHIMARU_1_nlbwuc.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOM3SANNINOROCHIMARU_2_dlcyop.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOM3SANNINOROCHIMARU_4_ztepiy.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOM3SANNINOROCHIMARU_5_gsctpa.webp',
    ],
  },
];
