export const PRODUCTS = [
  {
    id: 'G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY',
    name: 'Monkey D. Luffy',
    series: 'Four Emperors Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_000_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_7.png',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_6.png',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_8.png',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_5.png',
    ],
  },
  {
    id: 'G5STUDIOONEPIECETHEROADTOBEKING',
    name: 'Monkey D. Luffy',
    series: 'The Road To Be King',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 28_650_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOONEPIECETHEROADTOBEKING_10.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOONEPIECETHEROADTOBEKING_9.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOONEPIECETHEROADTOBEKING_8.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOONEPIECETHEROADTOBEKING_6.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOONEPIECETHEROADTOBEKING_2.png',
    ],
  },
  {
    id: 'G5STUDIOONEPIECEENMAFORMRORONOAZORO',
    name: 'Roronoa Zoro',
    series: 'Enma Form',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_300_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/files/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_5.png',
      'https://www.ffcollectibles.com.au/cdn/shop/files/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_4.png',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESLUFFY',
    name: 'Monkey D. Luffy',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 6_300_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESLUFFY_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESLUFFY_2.jpg',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESZORO',
    name: 'Roronoa Zoro',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESZORO_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESZORO_2.jpg',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESNAMI',
    name: 'Nami',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESSERIESNAMI_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESSERIESNAMI_4.jpg',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESUSOPP',
    name: 'Usopp',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESSERIESUSOPP_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESSERIESUSOPP_4.jpg',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESSANJI',
    name: 'Vinsmoke Sanji',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESSANJI_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESSANJI_2.jpg',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESCHOPPER',
    name: 'Tony Tony Chopper',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_2.jpg',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESROBIN',
    name: 'Nico Robin',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 6_300_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESROBIN_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESROBIN_4.jpg',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESFRANKY',
    name: 'Franky',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 6_100_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESFRANKY_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESFRANKY_2.jpg',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESBROOK',
    name: 'Brook',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESBROOK_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESBROOK_5.jpg',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESJINBE',
    name: 'Jinbe',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESJINBE_1.png',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOSTRAWHATPIRATESERIESJINBE_3.png',
    ],
  },
  {
    id: 'G5STUDIOYAMATO',
    name: 'Yamato',
    series: '',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOYAMATO_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/G5STUDIOYAMATO_4.jpg',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOHOKAGESERIES1.HASHIRAMASENJU',
    name: 'Senju Hashirama',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_500_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIO_NARUTOHOKAGESERIES1.HASHIRAMASENJU_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIO_NARUTOHOKAGESERIES1.HASHIRAMASENJU_5.jpg',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES2.TOBIRAMASENJU',
    name: 'Senju Tobirama',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_500_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES2.TOBIRAMASENJU_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES2.TOBIRAMASENJU_4.jpg',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIOSARUTOBI',
    name: 'Sarutobi Hiruzen',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_900_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIOSARUTOBI_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIOSARUTOBI_3.jpg',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIOWCFHOKAGESERIES4.MINATONAMIKAZE',
    name: 'Namikaze Minato',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_900_000,
    images: [
      'http://ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIOWCFHOKAGESERIES4.MINATONAMIKAZE_1.jpg',
      'http://ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIOWCFHOKAGESERIES4.MINATONAMIKAZE_3.jpg',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES5.TSUNADE',
    name: 'Senju Stunade',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_700_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES5.TSUNADE_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES5.TSUNADE_2.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES5.TSUNADE_4.jpg',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIOHOKAGESERIESWCFKAKASHI',
    name: 'Hatake Kakashi',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 2_100_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIOHOKAGESERIESWCFKAKASHI_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIOHOKAGESERIESWCFKAKASHI_4.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIOHOKAGESERIESWCFKAKASHI_3.jpg',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES7.NARUTO',
    name: 'Uzumaki Naruto',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 5_100_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES7.NARUTO_1.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES7.NARUTO_8.jpg',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES_HOKAGEROCK',
    name: 'Hokage Rock',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 6_100_000,
    images: [
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES_HOKAGEROCK_2.jpg',
      'https://www.ffcollectibles.com.au/cdn/shop/products/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES_HOKAGEROCK_1.jpg',
    ],
  },
];
