export const PRODUCTS = [
  {
    id: 'G5STUDIOHASHIRAMASENJU',
    name: 'Senju Hashirama',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 9_000_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHASHIRAMASENJU_2_dxgtps.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHASHIRAMASENJU_1_flw2wn.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHASHIRAMASENJU_4_qqqy6t.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHASHIRAMASENJU_3_merjm4.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHASHIRAMASENJU_5_gss1p5.webp',
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESMADARAUCHIHA',
    name: 'Uchiha Madara',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 9_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESMADARAUCHIHA_2_ga1nlj.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESMADARAUCHIHA_1_kp1yef.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESMADARAUCHIHA_3_sq0ogf.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESMADARAUCHIHA_4_tr6j8o.webp',
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIES',
    name: 'Namikaze Minato',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 8_400_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIES_3_z9a1n7.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIES_1_pxzr9g.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIES_4_oiezah.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIES_5_ni1v5s.webp',
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA',
    name: 'Uchiha Obito',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 9_000_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA_2_c6xclg.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA_1_qtiinu.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA_3_dl5pny.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA_4_y8pxsd.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA_6_ci2lfd.webp',
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESITACHIUCHIHA',
    name: 'Uchiha Itachi',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 9_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESITACHIUCHIHA_2_fyamvf.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESITACHIUCHIHA_1_vctoqz.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESITACHIUCHIHA_3_vicorm.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESITACHIUCHIHA_4_gybzbs.webp',
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESSASUKEUCHIHA',
    name: 'Uchiha Sasuke',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 9_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESSASUKEUCHIHA_2_hwrksy.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESSASUKEUCHIHA_1_ddw18o.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESSASUKEUCHIHA_3_bbdryr.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESSASUKEUCHIHA_4_pc94pz.webp',
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA',
    name: 'Jiraiya',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 8_200_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA_2_dnheee.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA_1_z2lxw3.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA_3_aniyud.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA_4_kvfnm2.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA_5_k6xiks.webp',
    ],
  },
  {
    id: 'G5STUDIOSIXPATHSOFPAIN',
    name: 'Six Paths Of Pain',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 14_850_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSIXPATHSOFPAIN_1_ftwje2.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSIXPATHSOFPAIN_2_wuglfx.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSIXPATHSOFPAIN_3_mcnbbh.webp',
    ],
  },
  {
    id: 'G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI',
    name: 'Uzumaki Naruto',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 18_650_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_2_tu5kbk.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_1_fp0qrq.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_4_wgdzvp.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_7_bb5wiz.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_6_ze4ci6.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_3_cipuug.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_5_yprcsb.webp',
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESGAARA',
    name: 'Gaara',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESGAARA_2_axwfzg.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESGAARA_1_wuj6gd.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESGAARA_5_m2m1ix.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESGAARA_3_dhpmki.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOHIGH-ENDCUSTOMSERIESGAARA_6_mtgeby.webp',
    ],
  },
  {
    id: 'G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA',
    name: 'Deidara',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 5_000_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA_2_njxnso.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA_1_qm7kmn.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA_3_ac0t19.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA_5_d87nqm.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA_4_bowwmo.webp',
    ],
  },
  {
    id: 'G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY',
    name: 'Might Guy',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY_3_m5sh01.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY_1_dlylzt.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY_4_rllku4.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY_2_ftr3aq.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY_5_ypma5y.webp',
    ],
  },
  {
    id: 'G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI',
    name: 'Hoshigaki Kisame',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 5_100_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI_2_kv7rws.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI_1_pwzmmu.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI_3_mrqiqi.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI_4_wmmysi.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI_5_tvgufm.webp',
    ],
  },
  {
    id: 'G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY',
    name: 'Monkey D. Luffy',
    series: 'Four Emperors Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_000_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_7_jfergr.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_1_chjdnv.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_6_mhh8ob.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_2_bf6iti.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_8_zfxxvy.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_3_nn5czs.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_5_jykp1n.webp',
    ],
  },
  {
    id: 'G5STUDIOONEPIECETHEROADTOBEKING',
    name: 'Monkey D. Luffy',
    series: 'The Road To Be King',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 28_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOONEPIECETHEROADTOBEKING_10_wdq6my.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOONEPIECETHEROADTOBEKING_9_qs0kmp.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOONEPIECETHEROADTOBEKING_8_faltis.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOONEPIECETHEROADTOBEKING_3_yqmkly.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOONEPIECETHEROADTOBEKING_7_t7dbyw.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOONEPIECETHEROADTOBEKING_2_zdcxcx.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOONEPIECETHEROADTOBEKING_6_ttkudp.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOONEPIECETHEROADTOBEKING_5_vqdlnb.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOONEPIECETHEROADTOBEKING_4_yfmvb3.webp',
    ],
  },
  {
    id: 'G5STUDIOONEPIECEENMAFORMRORONOAZORO',
    name: 'Roronoa Zoro',
    series: 'Enma Form',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_5_y3jy9u.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_1_s3vcwm.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_4_agwrkz.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_3_ws0pp9.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_2_kjabt9.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESLUFFY',
    name: 'Monkey D. Luffy',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 6_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESLUFFY_1_gyyxbk.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESLUFFY_6_ul1b70.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESLUFFY_3_ovbeyi.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESLUFFY_2_foyzua.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESLUFFY_4_rmhx1k.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESZORO',
    name: 'Roronoa Zoro',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESZORO_1_sfbppo.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESZORO_7_xzafyc.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESZORO_3_ut02ud.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESZORO_4_mt1u4a.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESZORO_2_jcsc3h.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESNAMI',
    name: 'Nami',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESSERIESNAMI_1_a0o0l8.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESSERIESNAMI_2_dc1la1.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESSERIESNAMI_4_zsscpc.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESSERIESNAMI_3_fwmkxp.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESUSOPP',
    name: 'Usopp',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESSERIESUSOPP_1_zdfmeg.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESSERIESUSOPP_2_xhub5g.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESSERIESUSOPP_4_wwzssy.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESSANJI',
    name: 'Vinsmoke Sanji',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESSANJI_1_bwouuo.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESSANJI_5_h5fzpi.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESSANJI_2_s2yeya.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESSANJI_3_ilyd3c.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESCHOPPER',
    name: 'Tony Tony Chopper',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_1_ss1ydb.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_3_jdqdbq.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_2_nrtsby.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_5_wwkwf9.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESROBIN',
    name: 'Nico Robin',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 6_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESROBIN_1_kisc1x.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESROBIN_2_rjad8j.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESROBIN_4_yw59uy.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESROBIN_3_pn9dez.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESFRANKY',
    name: 'Franky',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 6_100_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESFRANKY_1_ncnmtz.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESFRANKY_6_y2epwn.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESFRANKY_2_bq46jp.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESFRANKY_3_f4kcx2.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESFRANKY_4_csip0h.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESBROOK',
    name: 'Brook',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESBROOK_1_tz5gyd.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESBROOK_3_waeebd.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESBROOK_5_ce3n3p.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESBROOK_6_fahluw.webp',
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESJINBE',
    name: 'Jinbe',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESJINBE_1_d8ixa3.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESJINBE_1_gv6jwe.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESJINBE_3_ahmdwc.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOSTRAWHATPIRATESERIESJINBE_2_j68zg0.webp',
    ],
  },
  {
    id: 'G5STUDIOYAMATO',
    name: 'Yamato',
    series: '',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOYAMATO_1_xbejip.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOYAMATO_2_syorwi.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOYAMATO_3_ghokw3.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOYAMATO_4_lvphta.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOYAMATO_5_nzoism.webp',
    ],
  },
  {
    id: 'G5STUDIO_RENGOKU',
    name: 'Kyojuro Rengoku',
    series: 'Flame Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 3_100_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_RENGOKU_2_eer0ir.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_RENGOKU_1_qo9a4t.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_RENGOKU_3_ogfnto.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_RENGOKU_4_rthy71.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_RENGOKU_5_oszvxs.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_RENGOKU_6_bvzphr.jpg',
    ],
  },
  {
    id: 'G5STUDIO_ZENITSU',
    name: 'Agatsuma Zenitsu',
    series: 'Thunder Breathing',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_800_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ZENITSU_2_fom7f1.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ZENITSU_3_d859sn.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ZENITSU_1_zkmhwq.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ZENITSU_4_dy6qu8.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ZENITSU_5_mrbxsb.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ZENITSU_6_d0nzge.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ZENITSU_7_dnyl1c.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ZENITSU_8_fgexv6.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_ZENITSU_9_wakjcj.jpg',
    ],
  },
  {
    id: 'G5STUDIO_GIYU',
    name: 'Tomioka Giyu',
    series: 'Water Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_800_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_GIYU_5_zknov6.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_GIYU_1_hutf4d.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_GIYU_2_ssomqo.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_GIYU_4_lh6eju.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_GIYU_3_ngeoox.jpg',
    ],
  },
  {
    id: 'G5STUDIO_MITSURI',
    name: 'Kanroji Mitsuri',
    series: 'Love Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_850_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_MITSURI_2_vlas5h.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_MITSURI_1_wayac5.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_MITSURI_3_c5vbrh.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_MITSURI_4_sikzuc.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_MITSURI_5_xu4hiv.jpg',
    ],
  },
  {
    id: 'G5STUDIO_SANEMI',
    name: 'Shinazugawa Sanemi',
    series: 'Wind Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_800_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_SANEMI_1_wf9a8s.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_SANEMI_2_r8oysh.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_SANEMI_3_codgfv.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_SANEMI_4_lqxwiy.jpg',
    ],
  },
  {
    id: 'G5STUDIO_MUZAN',
    name: 'Kibutsuji Muzan',
    series: 'Demon King',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_800_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_MUZAN_2_yugz1s.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_MUZAN_1_vjtx4f.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_MUZAN_5_gjexbv.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_MUZAN_3_kmomuz.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_MUZAN_4_h5jna5.jpg',
    ],
  },
  {
    id: 'G5STUDIO_GYOMEI',
    name: 'Himejima Gyomei',
    series: 'Stone Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_800_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_GYOMEI_2_qb0hnj.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_GYOMEI_1_qkdiyr.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_GYOMEI_3_egt8ws.jpg',
    ],
  },
  {
    id: 'WATERBREATHINGTANJIRO',
    name: 'Kamado Tanjiro',
    series: 'Water Breathing',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 4_400_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/WATERBREATHINGTANJIRO_2_il2iwd.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/WATERBREATHINGTANJIRO_4_idbyaz.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/WATERBREATHINGTANJIRO_5_ch3xqm.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/WATERBREATHINGTANJIRO_3_zdreu7.webp',
    ],
  },
  {
    id: 'G5STUDIO_DEMONSLAYERFLAMEBREATHINGKYOJURORENGOKU',
    name: 'Kyojuro Rengoku',
    series: 'Flame Breathing',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 5_200_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_DEMONSLAYERFLAMEBREATHINGKYOJURORENGOKU_4_nhlbeb.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_DEMONSLAYERFLAMEBREATHINGKYOJURORENGOKU_3_g4qvzc.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_DEMONSLAYERFLAMEBREATHINGKYOJURORENGOKU_1_v6gfxe.webp',
    ],
  },
  {
    id: 'G5STUDIO_AKAZA',
    name: 'Akaza',
    series: 'Upper Moon 3',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 3_100_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_AKAZA_1_ubpmac.avif',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_AKAZA_2_xynimx.avif',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_AKAZA_3_ddpsia.avif',
    ],
  },
  {
    id: 'G5STUDIO_OBANAI',
    name: 'Iguro Obanai',
    series: 'Serpent Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_350_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_OBANAI_2_bjclyq.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_OBANAI_1_jpnd6m.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_OBANAI_3_brbhgm.jpg',
    ],
  },
  {
    id: 'G5STUDIO_TENGEN',
    name: 'Uzui Tengen',
    series: 'Sound Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_850_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_TENGEN_2_pz8q2j.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_TENGEN_1_gvi0sn.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_TENGEN_3_jrek5l.jpg',
    ],
  },
  {
    id: 'G5STUDIO_SHINOBU',
    name: 'Kocho Shinobu',
    series: 'Insect Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_350_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_SHINOBU_2_aisny3.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_SHINOBU_1_f6jbxa.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_SHINOBU_3_vznhub.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_SHINOBU_4_bxnfta.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_SHINOBU_5_jnbai8.jpg',
    ],
  },
  {
    id: 'G5STUDIO_MUICHIRO',
    name: 'Tokito Muichiro',
    series: 'Mist Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 3_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_MUICHIRO_2_imalot.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_MUICHIRO_1_arwqm9.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_MUICHIRO_3_cw18mz.jpg',
    ],
  },
  {
    id: 'G5STUDIO_YORIICHI_2',
    name: 'Tsugikuni Yoriichi',
    series: 'Sun Breathing',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_YORIICHI_3_tdiwzx.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_YORIICHI_1_rlvchd.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIO_YORIICHI_2_wfeerp.jpg',
    ],
  },
  {
    id: 'G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO',
    name: 'Kamado Tanjiro',
    series: 'Sun Breathing',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 4_050_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO_2_atpl6f.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO_1_i3cs9e.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO_4_v9gizn.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO_3_bjjyzj.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO_5_iq8ijp.webp',
    ],
  },
  {
    id: 'SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES1.ITACHIUCHIHA',
    name: 'Uchiha Itachi',
    series: 'Uchiha Clan Susanoo Series',
    studio: 'Surge Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 3_800_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES1.ITACHIUCHIHA_1_vkloss.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES1.ITACHIUCHIHA_7_zc8amh.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES1.ITACHIUCHIHA_8_szuhuj.webp',
    ],
  },
  {
    id: 'SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES2.MADARAUCHIHA',
    name: 'Uchiha Madara',
    series: 'Uchiha Clan Susanoo Series',
    studio: 'Surge Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 3_800_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES2.MADARAUCHIHA_1_oewk15.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES2.MADARAUCHIHA_2_zonbsj.jpg',
    ],
  },
  {
    id: 'SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES3.SASUKEUCHIHA',
    name: 'Uchiha Sasuke',
    series: 'Uchiha Clan Susanoo Series',
    studio: 'Surge Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 3_800_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES3.SASUKEUCHIHA_1_kyjv4h.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES3.SASUKEUCHIHA_2_cfeu3f.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES3.SASUKEUCHIHA_3_nrxrgi.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES3.SASUKEUCHIHA_4_dejgyh.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES3.SASUKEUCHIHA_5_tjstzf.jpg',
    ],
  },
  {
    id: 'SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES4.OBITOUCHIHA',
    name: 'Uchiha Obito',
    series: 'Uchiha Clan Susanoo Series',
    studio: 'Surge Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 3_800_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES4.OBITOUCHIHA_1_uhqb7l.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES4.OBITOUCHIHA_2_qlqozk.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES4.OBITOUCHIHA_3_ns9pws.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES4.OBITOUCHIHA_4_rqey8r.jpg',
    ],
  },
  {
    id: 'SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES.KAKASHI',
    name: 'Hakate Kakashi',
    series: 'Uchiha Clan Susanoo Series',
    studio: 'Surge Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 3_800_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES.KAKASHI_1_czxf02.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES.KAKASHI_2_duikht.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES.KAKASHI_3_bt9vsd.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES.KAKASHI_4_syoopo.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES.KAKASHI_5_qdwrb4.jpg',
    ],
  },
  {
    id: 'SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES5.SHISUIUCHIHA',
    name: 'Uchiha Shisui',
    series: 'Uchiha Clan Susanoo Series',
    studio: 'Surge Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 3_800_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES5.SHISUIUCHIHA_1_jxzfso.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES5.SHISUIUCHIHA_2_jcoigx.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/SURGESTUDIO_NARUTOWCFUCHIHACLANSUSANOOSERIES5.SHISUIUCHIHA_3_kg4p8n.jpg',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOHOKAGESERIES1.HASHIRAMASENJU',
    name: 'Senju Hashirama',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_500_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOHOKAGESERIES1.HASHIRAMASENJU_1_oy1wnh.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOHOKAGESERIES1.HASHIRAMASENJU_5_mfsu3u.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOHOKAGESERIES1.HASHIRAMASENJU_6_iyqk94.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOHOKAGESERIES1.HASHIRAMASENJU_7_f6l7yz.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOHOKAGESERIES1.HASHIRAMASENJU_8_haytmw.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOHOKAGESERIES1.HASHIRAMASENJU_9_kutord.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOHOKAGESERIES1.HASHIRAMASENJU_4_kivfjy.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES2.TOBIRAMASENJU',
    name: 'Senju Tobirama',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_500_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES2.TOBIRAMASENJU_1_niwh1a.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES2.TOBIRAMASENJU_4_bf97tt.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES2.TOBIRAMASENJU_5_bozxqu.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES2.TOBIRAMASENJU_6_k8u73h.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES2.TOBIRAMASENJU_7_blyisw.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES2.TOBIRAMASENJU_3_oohn7t.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIOSARUTOBI',
    name: 'Sarutobi Hiruzen',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOSARUTOBI_1_glxlqy.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOSARUTOBI_2_hjcg6r.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOSARUTOBI_3_ia3za9.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOSARUTOBI_4_yg3rlw.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIOWCFHOKAGESERIES4.MINATONAMIKAZE',
    name: 'Namikaze Minato',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOWCFHOKAGESERIES4.MINATONAMIKAZE_1_muoatf.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOWCFHOKAGESERIES4.MINATONAMIKAZE_2_cbkv6q.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOWCFHOKAGESERIES4.MINATONAMIKAZE_3_mwah3b.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES5.TSUNADE',
    name: 'Senju Stunade',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES5.TSUNADE_1_dfgb2z.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES5.TSUNADE_4_tl4sch.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES5.TSUNADE_3_ugmzu7.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES5.TSUNADE_2_nhyuox.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIOHOKAGESERIESWCFKAKASHI',
    name: 'Hatake Kakashi',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 2_100_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOHOKAGESERIESWCFKAKASHI_1_zqh7pm.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOHOKAGESERIESWCFKAKASHI_3_f9gxe5.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOHOKAGESERIESWCFKAKASHI_8_n5pgne.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOHOKAGESERIESWCFKAKASHI_2_xqyhpi.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOHOKAGESERIESWCFKAKASHI_4_jw1wr2.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES7.NARUTO',
    name: 'Uzumaki Naruto',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 5_100_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES7.NARUTO_1_c4z442.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES7.NARUTO_8_u2utz1.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES7.NARUTO_6_vxi9qi.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES7.NARUTO_5_w3njdh.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES7.NARUTO_7_viceov.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES_HOKAGEROCK',
    name: 'Hokage Rock',
    series: 'Hokage Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 6_100_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES_HOKAGEROCK_2_qtzwp9.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOWCFHOKAGESERIES_HOKAGEROCK_1_vhycvg.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIOJIRAIYA',
    name: 'Jiraiya',
    series: 'Sannin Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 2_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOJIRAIYA_1_tfa8dm.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOJIRAIYA_2_ggj1fa.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOJIRAIYA_3_hdmqpk.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOJIRAIYA_4_rxtfw9.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOJIRAIYA_5_i7znza.jpg',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIOTSUNADE',
    name: 'Senju Stunade',
    series: 'Sannin Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_100_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOTSUNADE_1_sumata.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOTSUNADE_2_fmz0xo.jpg',
    ],
  },
  {
    id: 'STONECUSTOM3SANNINOROCHIMARU',
    name: 'Orochimaru',
    series: 'Sannin Series',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 2_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOM3SANNINOROCHIMARU_1_m2jxnu.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOM3SANNINOROCHIMARU_2_xhegxc.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOM3SANNINOROCHIMARU_3_o5kset.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOM3SANNINOROCHIMARU_4_v3klgh.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOM3SANNINOROCHIMARU_5_r6n89r.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_HUMANPATH',
    name: 'Human Path',
    series: 'Six Paths Of Pain',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 2_200_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_HUMANPATH_1_ukzpfp.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_HUMANPATH_2_pymptq.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_HUMANPATH_3_va5my5.jpg',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_ANIMALPATH',
    name: 'Animal Path',
    series: 'Six Paths Of Pain',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 2_550_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_ANIMALPATH_1_siedsy.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_ANIMALPATH_2_wzkotb.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_ANIMALPATH_3_c0zpui.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_ANIMALPATH_4_a16ipe.jpg',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARAKAPATH',
    name: 'Naraka Path',
    series: 'Six Paths Of Pain',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 2_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOASURAANDNARAKAPATH_11_qd85qm.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARAKAPATH_1_zczz70.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOASURAANDNARAKAPATH_6_u1nafq.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOASURAANDNARAKAPATH_7_swkqqj.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOASURAANDNARAKAPATH_8_pkokxm.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_ASURAPATH',
    name: 'Asura Path',
    series: 'Six Paths Of Pain',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 2_750_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOASURAANDNARAKAPATH_10_aaaapt.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_ASURAPATH_1_v4vdtg.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOASURAANDNARAKAPATH_2_o2uz5t.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOASURAANDNARAKAPATH_3_errsbf.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOASURAANDNARAKAPATH_4_pum0ik.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_DEVAPATH',
    name: 'Deva Path',
    series: 'Six Paths Of Pain',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 3_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_DEVAPATH_1_t8ictc.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIODEVAANDPRETAPATH_8_i5ckyp.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIODEVAANDPRETAPATH_7_fcfotb.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIODEVAANDPRETAPATH_6_oc78p1.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIODEVAANDPRETAPATH_4_wfn14a.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIODEVAANDPRETAPATH_5_btfb0m.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_DEVAPATH_2_aosad8.jpg',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_PRETAPATH',
    name: 'Preta Path',
    series: 'Six Paths Of Pain',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 2_550_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_PRETAPATH_1_xe4iwu.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIODEVAANDPRETAPATH_9_kjcvci.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIODEVAANDPRETAPATH_10_n2ud2t.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIODEVAANDPRETAPATH_11_lnwut9.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIODEVAANDPRETAPATH_12_dveicr.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIODEVAANDPRETAPATH_13_icawta.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NAGATO',
    name: 'Nagato',
    series: 'Six Paths Of Pain',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 3_650_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOSIXPATHSOFPATH_NAGATOANDKONAN_1_ofvomn.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOSIXPATHSOFPATH_NAGATOANDKONAN_7_fu8gfr.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOSIXPATHSOFPATH_NAGATOANDKONAN_6_m7vhvj.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOSIXPATHSOFPATH_NAGATOANDKONAN_5_nkdzmo.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOSIXPATHSOFPATH_NAGATOANDKONAN_2_ryhmaq.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOSIXPATHSOFPATH_NAGATOANDKONAN_4_emweqv.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOSIXPATHSOFPATH_NAGATOANDKONAN_8_kfaadx.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_KONAN',
    name: 'Konan',
    series: 'Six Paths Of Pain',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_450_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOSIXPATHSOFPATH_NAGATOANDKONAN_11_jjfjbw.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIO_NARUTOSIXPATHSOFPATH_ANIMALPATH',
    name: 'Animal Path',
    series: 'Six Paths Of Pain',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 2_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOSIXPATHSOFPATH_ANIMALPATH_1_ems0be.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOSIXPATHSOFPATH_ANIMALPATH_5_rneyql.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOSIXPATHSOFPATH_ANIMALPATH_3_c3jhfa.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOSIXPATHSOFPATH_ANIMALPATH_5_rneyql.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOSIXPATHSOFPATH_ANIMALPATH_6_f3f1bk.webp',
    ],
  },
  {
    id: 'STONECUSTOMSTUDIOSIXPATHSOFPAINBUILDINGBASE',
    name: 'Building Base',
    series: 'Six Paths Of Pain',
    studio: 'Stone Custom Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 6_600_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIO_NARUTOSIXPATHSOFPATH_ANIMALPATH_2_ou39zu.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOSIXPATHSOFPAINBUILDINGBASE_6_aumpyl.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOSIXPATHSOFPAINBUILDINGBASE_7_micq0w.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOSIXPATHSOFPAINBUILDINGBASE_8_bppyfs.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/STONECUSTOMSTUDIOSIXPATHSOFPAINBUILDINGBASE_9_fwo8dc.webp',
    ],
  },
  {
    id: 'XSYANGSTUDIOKAIDO',
    name: 'Kaido',
    series: 'Yonko Series',
    studio: 'XS & Yang Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 4_600_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOKAIDO_1_fmqwlr.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOKAIDO_2_piub1k.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOKAIDO_3_cxh7ch.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOKAIDO_4_k2wks8.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOKAIDO_5_vehlim.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOKAIDO_6_mexuix.jpg',
    ],
  },
  {
    id: 'XSYANGSTUDIOWHITEBEARD',
    name: 'Edward Newgate (White Beard)',
    series: 'Yonko Series',
    studio: 'XS & Yang Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOWHITEBEARD_1_mb4wzc.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOWHITEBEARD_2_xlozun.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOWHITEBEARD_3_yi5odq.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOWHITEBEARD_4_vqsqok.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOWHITEBEARD_5_amoltl.jpg',
    ],
  },
  {
    id: 'XSYANGSTUDIOBIGMOM',
    name: 'Charlotte Linlin (Big Mom)',
    series: 'Yonko Series',
    studio: 'XS & Yang Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOBIGMOM_1_e9hdxx.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOBIGMOM_2_gztlod.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOBIGMOM_3_qksfmo.jpg',
    ],
  },
  {
    id: 'XSYANGSTUDIOSHANKS',
    name: 'Shanks (Red Haired)',
    series: 'Yonko Series',
    studio: 'XS & Yang Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_800_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOSHANKS_1_sj3gh3.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOSHANKS_2_szzkao.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOSHANKS_3_lewrsr.webp',
    ],
  },
  {
    id: 'XSYANGSTUDIOBLACKBEARD',
    name: 'Marshall D. Teach (Black Beard)',
    series: 'Yonko Series',
    studio: 'XS & Yang Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 4_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOBLACKBEARD_1_c7nwet.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOBLACKBEARD_2_z4owvo.webp',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOBLACKBEARD_3_l4a5aw.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOBLACKBEARD_4_ki15hf.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/XSYANGSTUDIOBLACKBEARD_5_cpeyel.jpg',
    ],
  },
  {
    id: 'TOYSTUDIOSAWADATSUNAYOSHI',
    name: 'Sawada Tsunayoshi',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/TOYSTUDIOSAWADATSUNAYOSHI_xbx2ds.jpg',
    ],
  },
  {
    id: 'TOYSTUDIOGOKUDERA',
    name: 'Hayato Gokudera',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_250_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/TOYSTUDIOGOKUDERA_1_hg7mub.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/TOYSTUDIOGOKUDERA_2_hd5y8r.jpg',
    ],
  },
  {
    id: 'TOYSTUDIOROKUDOUMUKURO',
    name: 'Rokudo Mukuro',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_300_000,
    images: ['https://res.cloudinary.com/dahbzn13g/image/upload/TOYSTUDIOROKUDOUMUKURO_i81gtn.jpg'],
  },
  {
    id: 'TOYSTUDIOHIBARIKYOYA',
    name: 'Kyoya Hibari',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_250_000,
    images: ['https://res.cloudinary.com/dahbzn13g/image/upload/TOYSTUDIOHIBARIKYOYA_iuiyjh.jpg'],
  },
  {
    id: 'TOYSTUDIORANBO1',
    name: 'Lambo',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_250_000,
    images: ['https://res.cloudinary.com/dahbzn13g/image/upload/TOYSTUDIORANBO_1_nbpyxg.jpg'],
  },
  {
    id: 'TOYSTUDIOKUROMU',
    name: 'Chrome Dokuro',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_250_000,
    images: ['https://res.cloudinary.com/dahbzn13g/image/upload/TOYSTUDIOKUROMU_adalm7.jpg'],
  },
  {
    id: 'TOYSTUDIOYAMAMOTO',
    name: 'Takeshi Yamamoto',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_300_000,
    images: ['https://res.cloudinary.com/dahbzn13g/image/upload/TOYSTUDIOYAMAMOTO_vyf0jo.jpg'],
  },
  {
    id: 'TOYSTUDIOSASAGAWA',
    name: 'Sasagawa Ryohei',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_700_000,
    images: ['https://res.cloudinary.com/dahbzn13g/image/upload/TOYSTUDIOSASAGAWA_hy6o7s.jpg'],
  },
  {
    id: 'TOYSTUDIORANBO2',
    name: 'Lambo',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_700_000,
    images: ['https://res.cloudinary.com/dahbzn13g/image/upload/TOYSTUDIORANBO_2_asy5ic.jpg'],
  },
  {
    id: 'OMOSTUDIO_SHICHIBUKAI_MIHAWK',
    name: 'Dracule Mihawk',
    series: 'Shichibukai',
    studio: 'OMO Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_400_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_MIHAWK_1_ky2t6l.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_MIHAWK_2_reagqn.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_MIHAWK_3_gq8yi2.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_MIHAWK_4_uuhd0s.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_MIHAWK_5_hv8ghg.jpg',
    ],
  },
  {
    id: 'OMOSTUDIO_SHICHIBUKAI_CROCODILE',
    name: 'Sir Crocodile',
    series: 'Shichibukai',
    studio: 'OMO Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_050_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_CROCODILE_1_eqbp5a.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_CROCODILE_2_ro8mpl.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_CROCODILE_3_h9ivrw.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_CROCODILE_4_o7ebpo.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_CROCODILE_5_qet4zl.jpg',
    ],
  },
  {
    id: 'OMOSTUDIO_SHICHIBUKAI_KUMA',
    name: 'Bartholomew Kuma',
    series: 'Shichibukai',
    studio: 'OMO Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_200_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_KUMA_1_mkdx5o.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_KUMA_2_wbs73h.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_KUMA_3_u88txw.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_KUMA_4_b8l4xz.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_KUMA_5_n2am1j.jpg',
    ],
  },
  {
    id: 'OMOSTUDIO_SHICHIBUKAI_MORIA',
    name: 'Gecko Moria',
    series: 'Shichibukai',
    studio: 'OMO Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_400_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_MORIA_1_zi6rdb.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_MORIA_2_bsbior.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_MORIA_3_xxx7q9.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_MORIA_4_f15h5t.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_MORIA_5_kmlpmy.jpg',
    ],
  },
  {
    id: 'OMOSTUDIO_SHICHIBUKAI_DOFLAMINGO',
    name: 'Donquixote Doflamingo',
    series: 'Shichibukai',
    studio: 'OMO Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_200_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_DOFLAMINGO_1_l1hw7s.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_DOFLAMINGO_2_txwkhi.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_DOFLAMINGO_3_h2fnu7.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_DOFLAMINGO_4_u1qney.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_DOFLAMINGO_5_uxkylg.jpg',
    ],
  },
  {
    id: 'OMOSTUDIO_SHICHIBUKAI_JINBE',
    name: 'Jinbe',
    series: 'Shichibukai',
    studio: 'OMO Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_200_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_JINBE_1_fq6ume.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_JINBE_2_bhrrsu.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_JINBE_3_buqvwi.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_JINBE_4_lzmp2a.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_JINBE_5_nea3j3.jpg',
    ],
  },
  {
    id: 'OMOSTUDIO_SHICHIBUKAI_HANCOCK',
    name: 'Boa Hancock',
    series: 'Shichibukai',
    studio: 'OMO Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_500_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_HANCOCK_1_dje5zj.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_HANCOCK_2_b9hn39.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_HANCOCK_3_plzlov.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_HANCOCK_4_mcyzcc.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_HANCOCK_5_ar7lo3.jpg',
    ],
  },
  {
    id: 'OMOSTUDIO_SHICHIBUKAI_TEACH',
    name: 'Marshall D. Teach (Black Beard)',
    series: 'Shichibukai',
    studio: 'OMO Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_TEACH_1_vvnaqd.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_TEACH_2_aecotd.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_TEACH_3_tgm7ww.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_TEACH_4_zdkoto.jpg',
    ],
  },
  {
    id: 'OMOSTUDIO_SHICHIBUKAI_LAW',
    name: 'Trafalgar D. Water Law',
    series: 'Shichibukai',
    studio: 'OMO Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_400_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_LAW_1_cjxzsi.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_LAW_2_fdk7e3.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_LAW_3_cqdjwc.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_LAW_4_zzuk97.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_LAW_5_qdzvea.jpg',
    ],
  },
  {
    id: 'OMOSTUDIO_SHICHIBUKAI_BUGGY',
    name: 'Buggy',
    series: 'Shichibukai',
    studio: 'OMO Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_400_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_BUGGY_1_yl6wam.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_BUGGY_2_rcehr8.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_BUGGY_3_klrmig.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_BUGGY_4_itgog4.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_BUGGY_5_uy2oxt.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/OMOSTUDIO_SHICHIBUKAI_BUGGY_6_ludqyv.jpg',
    ],
  },
  {
    id: 'KIDULTWORKSHOPSTUDIO_GONFREECSS',
    name: 'Gon Freecss',
    series: 'Hunter x Hunter',
    studio: 'Kidult Workshop Studio',
    material: 'Resin',
    type: 'Hunter x Hunter',
    price: 11_050_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_GONFREECSS_1_nnhomk.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_GONFREECSS_2_khcbxg.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_GONFREECSS_3_olnh3n.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_GONFREECSS_4_zgpk9b.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_GONFREECSS_5_ufgwra.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_GONFREECSS_6_xr1jxx.jpg',
    ],
  },
  {
    id: 'KIDULTWORKSHOPSTUDIO_KURAPIKA',
    name: 'Kurapika',
    series: 'Hunter x Hunter',
    studio: 'Kidult Workshop Studio',
    material: 'Resin',
    type: 'Hunter x Hunter',
    price: 13_400_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_KURAPIKA_1_pifsja.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_KURAPIKA_2_wv6yto.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_KURAPIKA_3_kxqcu7.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_KURAPIKA_4_yktpou.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_KURAPIKA_5_r40ect.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_KURAPIKA_6_qy41ff.jpg',
    ],
  },
  {
    id: 'KIDULTWORKSHOPSTUDIO_CHROLLOLUCILFER',
    name: 'Chrollo Lucilfer',
    series: 'Hunter x Hunter',
    studio: 'Kidult Workshop Studio',
    material: 'Resin',
    type: 'Hunter x Hunter',
    price: 12_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_CHROLLOLUCILFER_1_rzisxa.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_CHROLLOLUCILFER_2_n6f4jj.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_CHROLLOLUCILFER_3_s5tocj.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_CHROLLOLUCILFER_4_bclusw.jpg',
    ],
  },
  {
    id: 'KIDULTWORKSHOPSTUDIO_KILLUAZOLDYCK',
    name: 'Killua Zoldyck',
    series: 'Hunter x Hunter',
    studio: 'Kidult Workshop Studio',
    material: 'Resin',
    type: 'Hunter x Hunter',
    price: 15_500_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_KILLUAZOLDYCK_1_l1grjt.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_KILLUAZOLDYCK_2_df6ia5.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_KILLUAZOLDYCK_3_f05r2r.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_KILLUAZOLDYCK_4_mrsgub.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_KILLUAZOLDYCK_5_piockv.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/KIDULTWORKSHOPSTUDIO_KILLUAZOLDYCK_6_b1yirs.jpg',
    ],
  },
  {
    id: 'YZSTUDIO_EXPLUS_EUSTASSKID',
    name: 'Eustass Kid',
    series: 'Ex Plus Magnet Demon',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_000_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_EUSTASSKID_1_psqbpr.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_EUSTASSKID_2_vlpkot.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_EUSTASSKID_3_f3mybv.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_EUSTASSKID_4_rzftey.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_EUSTASSKID_5_tjleui.jpg',
    ],
  },
  {
    id: 'YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA',
    name: 'Bartholomew Kuma',
    series: 'Ex Plus',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 1_900_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_1_b4gq5i.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_2_wyf7ae.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_3_r3uyo2.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_4_ovnnvg.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_5_ub5sfv.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_6_a984av.jpg',
    ],
  },
  {
    id: 'YZSTUDIO_EXPLUS_RORONOAZORO',
    name: 'Roronoa Zoro',
    series: 'Ex Plus Flying Dragon Fire Blaze',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_600_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_RORONOAZORO_1_ybjirm.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_RORONOAZORO_2_crhptc.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_RORONOAZORO_3_nzudqq.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_RORONOAZORO_4_hkyj9i.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_RORONOAZORO_5_y6dsjb.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_RORONOAZORO_6_qrkp9r.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_RORONOAZORO_7_rfx0z6.jpg',
    ],
  },
  {
    id: 'YZSTUDIO_EXPLUS_KING',
    name: 'King',
    series: 'Ex Plus Omori Karyudon',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_300_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_KING_1_iorz3x.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_KING_2_axx57m.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_KING_3_x0n0g4.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_KING_4_nqm6p1.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_KING_5_pazxml.jpg',
    ],
  },
  {
    id: 'YZSTUDIO_EXPLUS_VINSMOKESANJI',
    name: 'Vinsmoke Sanji',
    series: 'Ex Plus Goodbye Germa Blue Fire',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_700_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_VINSMOKESANJI_1_ahpkqm.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_VINSMOKESANJI_2_lca1tc.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_VINSMOKESANJI_3_rhmgyq.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_VINSMOKESANJI_4_brop6d.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_VINSMOKESANJI_5_mfo9gs.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_VINSMOKESANJI_6_dqpljd.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_VINSMOKESANJI_7_favzsu.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_EXPLUS_VINSMOKESANJI_8_l6db3r.jpg',
    ],
  },
  {
    id: 'YZSTUDIO_BANKAI_TOSHIRO',
    name: 'Hitsugaya Toshiro',
    series: 'Bankai Series',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_000_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_TOSHIRO_1_swkk4p.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_TOSHIRO_2_vofen1.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_TOSHIRO_3_n1blrs.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_TOSHIRO_4_izy9is.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_TOSHIRO_5_uwa4aj.jpg',
    ],
  },
  {
    id: 'YZSTUDIO_BANKAI_AIZEN',
    name: 'Sosuke Aizen',
    series: 'Bankai Series',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_100_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_AIZEN_1_tt88kt.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_AIZEN_2_havpmp.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_AIZEN_3_oj0fxw.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_AIZEN_4_x1giaj.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_AIZEN_5_zrprp7.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_AIZEN_6_lnow6z.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_AIZEN_7_egrmdy.jpg',
    ],
  },
  {
    id: 'YZSTUDIO_BANKAI_BYAKUYA',
    name: 'Kuchiki Byakuya',
    series: 'Bankai Series',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_200_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_BYAKUYA_1_kgc3ib.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_BYAKUYA_2_g5crgz.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_BYAKUYA_3_vpl3cb.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_BYAKUYA_4_nasgor.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_BYAKUYA_5_cjgff2.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_BYAKUYA_6_zio1rc.jpg',
    ],
  },
  {
    id: 'YZSTUDIO_BANKAI_SHUNSUI',
    name: 'Kyoraku Shunsui',
    series: 'Bankai Series',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_200_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_SHUNSUI_1_uvglyp.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_SHUNSUI_2_nn2eck.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_SHUNSUI_3_n9tpwf.jpg',
    ],
  },
  {
    id: 'YZSTUDIO_BANKAI_UNOHANA',
    name: 'Retsu Unohana',
    series: 'Bankai Series',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_250_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_UNOHANA_1_nb9arw.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_UNOHANA_2_clgkhn.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_UNOHANA_3_nrjwnf.jpg',
    ],
  },
  {
    id: 'YZSTUDIO_BANKAI_MAYURI',
    name: 'Kurotsuchi Mayuri',
    series: 'Bankai Series',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 6_880_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_MAYURI_1_fxriaj.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_MAYURI_2_tx1bka.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_MAYURI_3_uileg6.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_MAYURI_4_uankil.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_MAYURI_5_w63wie.jpg',
    ],
  },
  {
    id: 'YZSTUDIO_BANKAI_YAMAMOTO',
    name: 'Genryusai Shigekuni Yamamoto',
    series: 'Bankai Series',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 1_950_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_YAMAMOTO_1_fi1niz.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_YAMAMOTO_2_les4n9.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_YAMAMOTO_3_plmxby.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_YAMAMOTO_4_oj7roa.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_YAMAMOTO_5_nfws0b.jpg',
    ],
  },
  {
    id: 'YZSTUDIO_BANKAI_SHINJI',
    name: 'Hirako Shinji',
    series: 'Bankai Series',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_950_000,
    images: [
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_SHINJI_1_dezggv.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_SHINJI_2_yeg2i5.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_SHINJI_3_dwqvtz.jpg',
      'https://res.cloudinary.com/dahbzn13g/image/upload/YZSTUDIO_BANKAI_SHINJI_4_bs5tqf.jpg',
    ],
  },
];
