export const BASE_IMAGE_URL = 'https://res.cloudinary.com/dahbzn13g/image/upload';
export const PRODUCTS = [
  {
    id: 'G5STUDIOHASHIRAMASENJU',
    name: 'Senju Hashirama',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 5_700_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHASHIRAMASENJU_2_dxgtps`,
      `${BASE_IMAGE_URL}/G5STUDIOHASHIRAMASENJU_1_flw2wn`,
      `${BASE_IMAGE_URL}/G5STUDIOHASHIRAMASENJU_4_qqqy6t`,
      `${BASE_IMAGE_URL}/G5STUDIOHASHIRAMASENJU_3_merjm4`,
      `${BASE_IMAGE_URL}/G5STUDIOHASHIRAMASENJU_5_gss1p5`,
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESMADARAUCHIHA',
    name: 'Uchiha Madara',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 6_000_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESMADARAUCHIHA_2_ga1nlj`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESMADARAUCHIHA_1_kp1yef`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESMADARAUCHIHA_4_tr6j8o`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESMADARAUCHIHA_3_sq0ogf`,
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIES',
    name: 'Namikaze Minato',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 5_700_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIES_3_z9a1n7`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIES_1_pxzr9g`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIES_5_ni1v5s`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIES_4_oiezah`,
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA',
    name: 'Uchiha Obito',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 6_100_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA_2_c6xclg`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA_1_qtiinu`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA_4_y8pxsd`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA_3_dl5pny`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA_6_ci2lfd`,
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESITACHIUCHIHA',
    name: 'Uchiha Itachi',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 6_700_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESITACHIUCHIHA_2_fyamvf`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESITACHIUCHIHA_1_vctoqz`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESITACHIUCHIHA_3_vicorm`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESITACHIUCHIHA_4_gybzbs`,
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESSASUKEUCHIHA',
    name: 'Uchiha Sasuke',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 6_550_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESSASUKEUCHIHA_2_hwrksy`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESSASUKEUCHIHA_1_ddw18o`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESSASUKEUCHIHA_3_bbdryr`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESSASUKEUCHIHA_4_pc94pz`,
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA',
    name: 'Jiraiya',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 6_250_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA_2_dnheee`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA_1_z2lxw3`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA_3_aniyud`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA_4_kvfnm2`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA_5_k6xiks`,
    ],
  },
  {
    id: 'G5STUDIOSIXPATHSOFPAIN',
    name: 'Six Paths Of Pain',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 8_700_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSIXPATHSOFPAIN_1_ftwje2`,
      `${BASE_IMAGE_URL}/G5STUDIOSIXPATHSOFPAIN_2_wuglfx`,
      `${BASE_IMAGE_URL}/G5STUDIOSIXPATHSOFPAIN_3_mcnbbh`,
    ],
  },
  {
    id: 'G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI',
    name: 'Uzumaki Naruto',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 9_800_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_2_tu5kbk`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_1_fp0qrq`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_7_bb5wiz`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_4_wgdzvp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_6_ze4ci6`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_3_cipuug`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_5_yprcsb`,
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESGAARA',
    name: 'Gaara',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 6_100_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESGAARA_2_axwfzg`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESGAARA_1_wuj6gd`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESGAARA_5_m2m1ix`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESGAARA_3_dhpmki`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESGAARA_6_mtgeby`,
    ],
  },
  {
    id: 'G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA',
    name: 'Deidara',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 6_700_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA_2_njxnso`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA_1_qm7kmn`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA_3_ac0t19`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA_5_d87nqm`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA_4_bowwmo`,
    ],
  },
  {
    id: 'G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY',
    name: 'Might Guy',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 6_300_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY_3_m5sh01`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY_1_dlylzt`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY_2_ftr3aq`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY_4_rllku4`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY_5_ypma5y`,
    ],
  },
  {
    id: 'G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI',
    name: 'Hoshigaki Kisame',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 6_700_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI_2_kv7rws`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI_1_pwzmmu`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI_4_wmmysi`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI_3_mrqiqi`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI_5_tvgufm`,
    ],
  },
  {
    id: 'G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY',
    name: 'Monkey D. Luffy',
    series: 'Four Emperors',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_000_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_7_jfergr`,
      `${BASE_IMAGE_URL}/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_1_chjdnv`,
      `${BASE_IMAGE_URL}/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_6_mhh8ob`,
      `${BASE_IMAGE_URL}/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_3_nn5czs`,
      `${BASE_IMAGE_URL}/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_2_bf6iti`,
      `${BASE_IMAGE_URL}/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_8_zfxxvy`,
      `${BASE_IMAGE_URL}/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_5_jykp1n`,
    ],
  },
  {
    id: 'G5STUDIOONEPIECETHEROADTOBEKING',
    name: 'Monkey D. Luffy',
    series: 'The Road To Be King',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 14_200_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_10_wdq6my`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_2_zdcxcx`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_9_qs0kmp`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_8_faltis`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_3_yqmkly`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_7_t7dbyw`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_6_ttkudp`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_5_vqdlnb`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_4_yfmvb3`,
    ],
  },
  {
    id: 'G5STUDIO_ONEPIECEENMAFORMRORONOAZORO',
    name: 'Roronoa Zoro',
    series: 'Enma Form',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_200_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_5_y3jy9u`,
      `${BASE_IMAGE_URL}/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_1_s3vcwm`,
      `${BASE_IMAGE_URL}/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_3_ws0pp9`,
      `${BASE_IMAGE_URL}/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_4_agwrkz`,
      `${BASE_IMAGE_URL}/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_2_kjabt9`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESLUFFY',
    name: 'Monkey D. Luffy',
    series: 'Straw Hat Pirates',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_800_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESLUFFY_1_gyyxbk`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESLUFFY_6_ul1b70`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESLUFFY_3_ovbeyi`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESLUFFY_2_foyzua`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESLUFFY_4_rmhx1k`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESZORO',
    name: 'Roronoa Zoro',
    series: 'Straw Hat Pirates',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_950_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESZORO_1_sfbppo`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESZORO_7_xzafyc`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESZORO_3_ut02ud`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESZORO_4_mt1u4a`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESZORO_2_jcsc3h`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESNAMI',
    name: 'Nami',
    series: 'Straw Hat Pirates',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 4_000_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESSERIESNAMI_1_a0o0l8`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESSERIESNAMI_2_dc1la1`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESSERIESNAMI_4_zsscpc`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESSERIESNAMI_3_fwmkxp`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESUSOPP',
    name: 'Usopp',
    series: 'Straw Hat Pirates',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_600_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESSERIESUSOPP_1_zdfmeg`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESSERIESUSOPP_2_xhub5g`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESSERIESUSOPP_4_wwzssy`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESSERIESUSOPP_5_vzuspa`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESSANJI',
    name: 'Vinsmoke Sanji',
    series: 'Straw Hat Pirates',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_900_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESSANJI_1_bwouuo`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESSANJI_5_h5fzpi`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESSANJI_2_s2yeya`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESSANJI_3_ilyd3c`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESCHOPPER',
    name: 'Tony Tony Chopper',
    series: 'Straw Hat Pirates',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_950_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_1_ss1ydb`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_3_jdqdbq`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_2_nrtsby`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_5_wwkwf9`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESROBIN',
    name: 'Nico Robin',
    series: 'Straw Hat Pirates',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_600_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESROBIN_1_kisc1x`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESROBIN_2_rjad8j`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESROBIN_4_yw59uy`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESROBIN_3_pn9dez`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESFRANKY',
    name: 'Franky',
    series: 'Straw Hat Pirates',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_850_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESFRANKY_1_ncnmtz`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESFRANKY_6_y2epwn`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESFRANKY_3_f4kcx2`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESFRANKY_2_bq46jp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESFRANKY_4_csip0h`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESBROOK',
    name: 'Brook',
    series: 'Straw Hat Pirates',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_950_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESBROOK_1_tz5gyd`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESBROOK_3_waeebd`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESBROOK_5_ce3n3p`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESBROOK_6_fahluw`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESJINBE',
    name: 'Jinbe',
    series: 'Straw Hat Pirates',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_850_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESJINBE_1_d8ixa3`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESJINBE_1_gv6jwe`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESJINBE_3_ahmdwc`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESJINBE_2_j68zg0`,
    ],
  },
  {
    id: 'G5STUDIOYAMATO',
    name: 'Yamato',
    series: '',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 4_000_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOYAMATO_1_xbejip`,
      `${BASE_IMAGE_URL}/G5STUDIOYAMATO_2_syorwi`,
      `${BASE_IMAGE_URL}/G5STUDIOYAMATO_5_nzoism`,
      `${BASE_IMAGE_URL}/G5STUDIOYAMATO_4_lvphta`,
      `${BASE_IMAGE_URL}/G5STUDIOYAMATO_3_ghokw3`,
    ],
  },
  {
    id: 'G5STUDIO_RENGOKU',
    name: 'Kyojuro Rengoku',
    series: 'Flame Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 3_100_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_RENGOKU_2_eer0ir`,
      `${BASE_IMAGE_URL}/G5STUDIO_RENGOKU_1_qo9a4t`,
      `${BASE_IMAGE_URL}/G5STUDIO_RENGOKU_3_ogfnto`,
      `${BASE_IMAGE_URL}/G5STUDIO_RENGOKU_4_rthy71`,
      `${BASE_IMAGE_URL}/G5STUDIO_RENGOKU_5_oszvxs`,
      `${BASE_IMAGE_URL}/G5STUDIO_RENGOKU_6_bvzphr`,
    ],
  },
  {
    id: 'G5STUDIO_ZENITSU',
    name: 'Agatsuma Zenitsu',
    series: 'Thunder Breathing',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_800_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_2_fom7f1`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_3_d859sn`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_1_zkmhwq`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_4_dy6qu8`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_5_mrbxsb`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_6_d0nzge`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_7_dnyl1c`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_8_fgexv6`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_9_wakjcj`,
    ],
  },
  {
    id: 'G5STUDIO_GIYU',
    name: 'Tomioka Giyu',
    series: 'Water Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_800_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_GIYU_5_zknov6`,
      `${BASE_IMAGE_URL}/G5STUDIO_GIYU_1_hutf4d`,
      `${BASE_IMAGE_URL}/G5STUDIO_GIYU_2_ssomqo`,
      `${BASE_IMAGE_URL}/G5STUDIO_GIYU_4_lh6eju`,
      `${BASE_IMAGE_URL}/G5STUDIO_GIYU_3_ngeoox`,
    ],
  },
  {
    id: 'G5STUDIO_MITSURI',
    name: 'Kanroji Mitsuri',
    series: 'Love Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_850_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_MITSURI_2_vlas5h`,
      `${BASE_IMAGE_URL}/G5STUDIO_MITSURI_1_wayac5`,
      `${BASE_IMAGE_URL}/G5STUDIO_MITSURI_3_c5vbrh`,
      `${BASE_IMAGE_URL}/G5STUDIO_MITSURI_4_sikzuc`,
      `${BASE_IMAGE_URL}/G5STUDIO_MITSURI_5_xu4hiv`,
    ],
  },
  {
    id: 'G5STUDIO_SANEMI',
    name: 'Shinazugawa Sanemi',
    series: 'Wind Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_800_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_SANEMI_1_wf9a8s`,
      `${BASE_IMAGE_URL}/G5STUDIO_SANEMI_2_r8oysh`,
      `${BASE_IMAGE_URL}/G5STUDIO_SANEMI_3_codgfv`,
      `${BASE_IMAGE_URL}/G5STUDIO_SANEMI_4_lqxwiy`,
    ],
  },
  {
    id: 'G5STUDIO_MUZAN',
    name: 'Kibutsuji Muzan',
    series: 'Demon King',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_800_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_MUZAN_2_yugz1s`,
      `${BASE_IMAGE_URL}/G5STUDIO_MUZAN_1_vjtx4f`,
      `${BASE_IMAGE_URL}/G5STUDIO_MUZAN_5_gjexbv`,
      `${BASE_IMAGE_URL}/G5STUDIO_MUZAN_3_kmomuz`,
      `${BASE_IMAGE_URL}/G5STUDIO_MUZAN_4_h5jna5`,
    ],
  },
  {
    id: 'G5STUDIO_GYOMEI',
    name: 'Himejima Gyomei',
    series: 'Stone Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_800_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_GYOMEI_2_qb0hnj`,
      `${BASE_IMAGE_URL}/G5STUDIO_GYOMEI_1_qkdiyr`,
      `${BASE_IMAGE_URL}/G5STUDIO_GYOMEI_3_egt8ws`,
    ],
  },
  {
    id: 'WATERBREATHINGTANJIRO',
    name: 'Kamado Tanjiro',
    series: 'Water Breathing',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 4_400_000,
    images: [
      `${BASE_IMAGE_URL}/WATERBREATHINGTANJIRO_2_il2iwd`,
      `${BASE_IMAGE_URL}/WATERBREATHINGTANJIRO_4_idbyaz`,
      `${BASE_IMAGE_URL}/WATERBREATHINGTANJIRO_5_ch3xqm`,
      `${BASE_IMAGE_URL}/WATERBREATHINGTANJIRO_3_zdreu7`,
    ],
  },
  {
    id: 'G5STUDIO_DEMONSLAYERFLAMEBREATHINGKYOJURORENGOKU',
    name: 'Kyojuro Rengoku',
    series: 'Flame Breathing',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 5_200_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_DEMONSLAYERFLAMEBREATHINGKYOJURORENGOKU_4_nhlbeb`,
      `${BASE_IMAGE_URL}/G5STUDIO_DEMONSLAYERFLAMEBREATHINGKYOJURORENGOKU_3_g4qvzc`,
      `${BASE_IMAGE_URL}/G5STUDIO_DEMONSLAYERFLAMEBREATHINGKYOJURORENGOKU_1_v6gfxe`,
    ],
  },
  {
    id: 'G5STUDIO_AKAZA',
    name: 'Akaza',
    series: 'Upper Moon 3',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 3_100_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_AKAZA_1_ubpmac`,
      `${BASE_IMAGE_URL}/G5STUDIO_AKAZA_2_xynimx`,
      `${BASE_IMAGE_URL}/G5STUDIO_AKAZA_3_ddpsia`,
    ],
  },
  {
    id: 'G5STUDIO_OBANAI',
    name: 'Iguro Obanai',
    series: 'Serpent Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_350_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_OBANAI_2_bjclyq`,
      `${BASE_IMAGE_URL}/G5STUDIO_OBANAI_1_jpnd6m`,
      `${BASE_IMAGE_URL}/G5STUDIO_OBANAI_3_brbhgm`,
    ],
  },
  {
    id: 'G5STUDIO_TENGEN',
    name: 'Uzui Tengen',
    series: 'Sound Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_850_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_TENGEN_2_pz8q2j`,
      `${BASE_IMAGE_URL}/G5STUDIO_TENGEN_1_gvi0sn`,
      `${BASE_IMAGE_URL}/G5STUDIO_TENGEN_3_jrek5l`,
    ],
  },
  {
    id: 'G5STUDIO_SHINOBU',
    name: 'Kocho Shinobu',
    series: 'Insect Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_350_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_SHINOBU_2_aisny3`,
      `${BASE_IMAGE_URL}/G5STUDIO_SHINOBU_1_f6jbxa`,
      `${BASE_IMAGE_URL}/G5STUDIO_SHINOBU_3_vznhub`,
      `${BASE_IMAGE_URL}/G5STUDIO_SHINOBU_4_bxnfta`,
      `${BASE_IMAGE_URL}/G5STUDIO_SHINOBU_5_jnbai8`,
    ],
  },
  {
    id: 'G5STUDIO_MUICHIRO',
    name: 'Tokito Muichiro',
    series: 'Mist Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 3_700_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_MUICHIRO_2_imalot`,
      `${BASE_IMAGE_URL}/G5STUDIO_MUICHIRO_1_arwqm9`,
      `${BASE_IMAGE_URL}/G5STUDIO_MUICHIRO_3_cw18mz`,
    ],
  },
  {
    id: 'G5STUDIO_YORIICHI_2',
    name: 'Tsugikuni Yoriichi',
    series: 'Sun Breathing',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_300_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_YORIICHI_3_tdiwzx`,
      `${BASE_IMAGE_URL}/G5STUDIO_YORIICHI_1_rlvchd`,
      `${BASE_IMAGE_URL}/G5STUDIO_YORIICHI_2_wfeerp`,
    ],
  },
  {
    id: 'G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO',
    name: 'Kamado Tanjiro',
    series: 'Sun Breathing',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 4_050_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO_2_atpl6f`,
      `${BASE_IMAGE_URL}/G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO_1_i3cs9e`,
      `${BASE_IMAGE_URL}/G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO_4_v9gizn`,
      `${BASE_IMAGE_URL}/G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO_3_bjjyzj`,
      `${BASE_IMAGE_URL}/G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO_5_iq8ijp`,
    ],
  },
  {
    id: 'TOYSTUDIOSAWADATSUNAYOSHI',
    name: 'Sawada Tsunayoshi',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_300_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIOSAWADATSUNAYOSHI_xbx2ds`],
  },
  {
    id: 'TOYSTUDIOGOKUDERA',
    name: 'Hayato Gokudera',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_250_000,
    images: [
      `${BASE_IMAGE_URL}/TOYSTUDIOGOKUDERA_1_hg7mub`,
      `${BASE_IMAGE_URL}/TOYSTUDIOGOKUDERA_2_hd5y8r`,
    ],
  },
  {
    id: 'TOYSTUDIOROKUDOUMUKURO',
    name: 'Rokudo Mukuro',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_300_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIOROKUDOUMUKURO_i81gtn`],
  },
  {
    id: 'TOYSTUDIOHIBARIKYOYA',
    name: 'Kyoya Hibari',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_250_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIOHIBARIKYOYA_iuiyjh`],
  },
  {
    id: 'TOYSTUDIORANBO1',
    name: 'Lambo',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_250_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIORANBO_1_nbpyxg`],
  },
  {
    id: 'TOYSTUDIOKUROMU',
    name: 'Chrome Dokuro',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_250_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIOKUROMU_adalm7`],
  },
  {
    id: 'TOYSTUDIOYAMAMOTO',
    name: 'Takeshi Yamamoto',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_300_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIOYAMAMOTO_vyf0jo`],
  },
  {
    id: 'TOYSTUDIOSASAGAWA',
    name: 'Sasagawa Ryohei',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_700_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIOSASAGAWA_hy6o7s`],
  },
  {
    id: 'TOYSTUDIORANBO2',
    name: 'Lambo',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_700_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIORANBO_2_asy5ic`],
  },
  {
    id: 'TOYSTUDIOGIOTTO',
    name: 'Giotto (Sawada Ieyasu)',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_600_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIOGIOTTO_igivkd`],
  },
  {
    id: 'TOYSTUDIO_NATSU',
    name: 'Natsu',
    series: 'Fairy Tail',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Fairy Tail',
    price: 2_400_000,
    images: [
      `${BASE_IMAGE_URL}/TOYSTUDIO_NATSU_1_cvfu65`,
      `${BASE_IMAGE_URL}/TOYSTUDIO_NATSU_2_fr0pvh`,
    ],
  },
  {
    id: 'YZSTUDIO_EXPLUS_EUSTASSKID',
    name: 'Eustass Kid',
    series: 'Ex Plus Magnet Demon',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_000_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_EUSTASSKID_1_psqbpr`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_EUSTASSKID_2_vlpkot`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_EUSTASSKID_3_f3mybv`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_EUSTASSKID_4_rzftey`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_EUSTASSKID_5_tjleui`,
    ],
  },
  {
    id: 'YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA',
    name: 'Bartholomew Kuma',
    series: 'Ex Plus',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 1_900_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_1_b4gq5i`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_2_wyf7ae`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_3_r3uyo2`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_4_ovnnvg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_5_ub5sfv`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_6_a984av`,
    ],
  },
  {
    id: 'YZSTUDIO_EXPLUS_RORONOAZORO',
    name: 'Roronoa Zoro',
    series: 'Ex Plus Flying Dragon Fire Blaze',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_600_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_RORONOAZORO_1_ybjirm`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_RORONOAZORO_2_crhptc`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_RORONOAZORO_3_nzudqq`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_RORONOAZORO_4_hkyj9i`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_RORONOAZORO_5_y6dsjb`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_RORONOAZORO_6_qrkp9r`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_RORONOAZORO_7_rfx0z6`,
    ],
  },
  {
    id: 'YZSTUDIO_EXPLUS_KING',
    name: 'King',
    series: 'Ex Plus Omori Karyudon',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_300_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_KING_1_iorz3x`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_KING_2_axx57m`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_KING_3_x0n0g4`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_KING_4_nqm6p1`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_KING_5_pazxml`,
    ],
  },
  {
    id: 'YZSTUDIO_EXPLUS_VINSMOKESANJI',
    name: 'Vinsmoke Sanji',
    series: 'Ex Plus Goodbye Germa Blue Fire',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_700_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_1_ahpkqm`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_2_lca1tc`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_3_rhmgyq`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_4_brop6d`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_5_mfo9gs`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_6_dqpljd`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_7_favzsu`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_8_l6db3r`,
    ],
  },
  {
    id: 'YZSTUDIO_EC001_TOSHIRO',
    name: 'Hitsugaya Toshiro: Daiguren Hyorinmaru',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_000_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC001_TOSHIRO_1_swkk4p`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC001_TOSHIRO_2_vofen1`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC001_TOSHIRO_3_n1blrs`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC001_TOSHIRO_4_izy9is`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC001_TOSHIRO_5_uwa4aj`,
    ],
  },
  {
    id: 'YZSTUDIO_EC002_AIZEN',
    name: 'Aizen Sokuke: Goryutenmetsu',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_200_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC002_AIZEN_1_tt88kt`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC002_AIZEN_2_havpmp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC002_AIZEN_3_oj0fxw`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC002_AIZEN_4_x1giaj`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC002_AIZEN_5_zrprp7`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC002_AIZEN_6_lnow6z`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC002_AIZEN_7_egrmdy`,
    ],
  },
  {
    id: 'YZSTUDIO_EC003_BYAKUYA',
    name: 'Kuchiki Byakuya: Senbonzakura Kageyoshi',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_200_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC003_BYAKUYA_1_kgc3ib`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC003_BYAKUYA_2_g5crgz`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC003_BYAKUYA_3_vpl3cb`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC003_BYAKUYA_4_nasgor`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC003_BYAKUYA_5_cjgff2`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC003_BYAKUYA_6_zio1rc`,
    ],
  },
  {
    id: 'YZSTUDIO_EC004_SHUNSUI',
    name: 'Kyoraku Shunsui: Katen Kyokotsu Karamatsu Shinju',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_200_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC004_SHUNSUI_1_uvglyp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC004_SHUNSUI_2_nn2eck`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC004_SHUNSUI_3_n9tpwf`,
    ],
  },
  {
    id: 'YZSTUDIO_EC005_RETSU',
    name: 'Unohana Retsu: Minazuki',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_250_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC005_RETSU_1_nb9arw`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC005_RETSU_2_clgkhn`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC005_RETSU_3_nrjwnf`,
    ],
  },
  {
    id: 'YZSTUDIO_EC006_MAYURI',
    name: 'Kurotsuchi Mayuri: Konjiki Ashisogi Jizo Matai Fukuin Shotai',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 7_000_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC006_MAYURI_1_fxriaj`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC006_MAYURI_2_tx1bka`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC006_MAYURI_3_uileg6`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC006_MAYURI_4_uankil`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC006_MAYURI_5_w63wie`,
    ],
  },
  {
    id: 'YZSTUDIO_EC007_YAMAMOTO',
    name: 'Yamamoto Genryusai Shigekuni: Zanka No Tachi',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 1_950_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC007_YAMAMOTO_1_fi1niz`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC007_YAMAMOTO_2_les4n9`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC007_YAMAMOTO_3_plmxby`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC007_YAMAMOTO_4_oj7roa`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC007_YAMAMOTO_5_nfws0b`,
    ],
  },
  {
    id: 'YZSTUDIO_EC008_SHINJI',
    name: 'Hirako Shinji: Sakashima Yokoshima Happofusagari',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_750_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC008_SHINJI_1_dezggv`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC008_SHINJI_2_yeg2i5`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC008_SHINJI_3_dwqvtz`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC008_SHINJI_4_bs5tqf`,
    ],
  },
  {
    id: 'YZSTUDIO_EC009_URAHARA',
    name: 'Urahara Kisuke: Kannonbiraki Benihime Aratame',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 3_000_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC009_URAHARA_1_xjbiwh`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC009_URAHARA_2_a1kccd`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC009_URAHARA_3_ff3jog`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC009_URAHARA_4_qmncxf`,
    ],
  },
  {
    id: 'YZSTUDIO_EC010_GRIMMJOW',
    name: 'Grimmjow Jaegerjaquez: Pantera Resurreccion',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 1_700_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_1_kinnpp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_2_wap10z`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_3_fkys1d`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_4_nsq9et`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_5_knmvix`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_6_rze9ay`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_7_ogfdlv`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_8_eadhiw`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_9_yfgmrj`,
    ],
  },
  {
    id: 'YZSTUDIO_EC011_YHWACH',
    name: 'Yhwach: Soul King',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 3_750_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC011_YHWACH_1_wlrdea`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC011_YHWACH_2_iw9rtv`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC011_YHWACH_3_j3obhv`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC011_YHWACH_4_lch4bf`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC011_YHWACH_5_rkg88l`,
    ],
  },
  {
    id: 'YZSTUDIO_EC012_ICHIGO',
    name: 'Kurosaki Ichigo: Tensa Zangetsu',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_050_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC012_ICHIGO_1_hlch2m`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC012_ICHIGO_2_zxevcf`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC012_ICHIGO_3_uhufwo`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC012_ICHIGO_4_mglns8`,
    ],
  },
  {
    id: 'YZSTUDIO_EC013_INOUE',
    name: 'Inoue Orihime: Shun Shun Rikka',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_050_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC013_INOUE_1_zjkk8f`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC013_INOUE_2_kajzf3`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC013_INOUE_3_jrdkwl`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC013_INOUE_4_wsnely`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC013_INOUE_5_zy2eep`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC013_INOUE_6_tn7zz7`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC013_INOUE_7_ht5xpn`,
    ],
  },
  {
    id: 'YZSTUDIO_EC014_KENPACHI',
    name: 'Zaraki Kenpachi',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_850_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC014_KENPACHI_1_odze0n`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC014_KENPACHI_2_hyfhcp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC014_KENPACHI_4_mlthvz`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC014_KENPACHI_6_wfg989`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC014_KENPACHI_3_gnezfl`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC014_KENPACHI_5_qkftom`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC014_KENPACHI_7_kbzqum`,
    ],
  },
  {
    id: 'APLUSSTUDIO_SAKAZUKI',
    name: 'Sakazuki (Akainu)',
    series: 'Navy Admiral',
    studio: 'A+ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_400_000,
    images: [
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_SAKAZUKI_1_cxbtpy`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_SAKAZUKI_2_oiimjj`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_SAKAZUKI_3_o6wzgj`,
    ],
  },
  {
    id: 'APLUSSTUDIO_KUZAN',
    name: 'Kuzan (Aokiji)',
    series: 'Navy Admiral',
    studio: 'A+ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_450_000,
    images: [
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_KUZAN_1_ealqhj`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_KUZAN_2_jfza2d`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_KUZAN_3_niqib7`,
    ],
  },
  {
    id: 'APLUSSTUDIO_BORSALINO',
    name: 'Borsalino (Kizaru)',
    series: 'Navy Admiral',
    studio: 'A+ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_600_000,
    images: [
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_BORSALINO_1_r1vmrv`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_BORSALINO_2_ohfi4z`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_BORSALINO_3_jzheci`,
    ],
  },
  {
    id: 'APLUSSTUDIO_ISSHO',
    name: 'Issho (Fujitora)',
    series: 'Navy Admiral',
    studio: 'A+ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_650_000,
    images: [
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_ISSHO_1_zvxcfi`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_ISSHO_2_vx4fih`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_ISSHO_3_yr4hvt`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_ISSHO_4_wis7lw`,
    ],
  },
  {
    id: 'APLUSSTUDIO_ARAMAKI',
    name: 'Aramaki (Ryokugyu)',
    series: 'Navy Admiral',
    studio: 'A+ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_700_000,
    images: [
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_ARAMAKI_1_j7bir4`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_ARAMAKI_2_hgjwfy`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_ARAMAKI_3_ukhjhv`,
    ],
  },
  {
    id: 'JLSTUDIO_KAKASHI',
    name: 'Hatake Kakashi',
    series: '',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_500_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_KAKASHI_1_ez1war`,
      `${BASE_IMAGE_URL}/JLSTUDIO_KAKASHI_2_ybkwoq`,
      `${BASE_IMAGE_URL}/JLSTUDIO_KAKASHI_3_giztgg`,
    ],
  },
  {
    id: 'JLSTUDIO_OBITO',
    name: 'Uchiha Obito',
    series: '',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_600_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_OBITO_1_uadhd1`,
      `${BASE_IMAGE_URL}/JLSTUDIO_OBITO_2_vwavls`,
      `${BASE_IMAGE_URL}/JLSTUDIO_OBITO_3_eyh9mx`,
    ],
  },
  {
    id: 'JLSTUDIO_GUY',
    name: 'Might Guy',
    series: '',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_600_000,
    images: [`${BASE_IMAGE_URL}/JLSTUDIO_GUY_1_curqnh`, `${BASE_IMAGE_URL}/JLSTUDIO_GUY_2_psgdmk`],
  },
  {
    id: 'JLSTUDIO_MADARA',
    name: 'Uchiha Madara',
    series: '',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_650_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_MADARA_1_kkwwg7`,
      `${BASE_IMAGE_URL}/JLSTUDIO_MADARA_2_whzzbn`,
      `${BASE_IMAGE_URL}/JLSTUDIO_MADARA_3_teo0ig`,
    ],
  },
  {
    id: 'JLSTUDIO_ITACHI',
    name: 'Uchiha Itachi',
    series: 'Akatsuki',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_650_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_ITACHI_1_mvtudm`,
      `${BASE_IMAGE_URL}/JLSTUDIO_ITACHI_2_ceuypl`,
    ],
  },
  {
    id: 'JLSTUDIO_SASORI',
    name: 'Sasori',
    series: 'Akatsuki',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_650_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_SASORI_1_daztve`,
      `${BASE_IMAGE_URL}/JLSTUDIO_SASORI_2_mged0k`,
    ],
  },
  {
    id: 'JLSTUDIO_HASHIRAMA',
    name: 'Senju Hashirama',
    series: '',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_700_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_HASHIRAMA_1_eal5jd`,
      `${BASE_IMAGE_URL}/JLSTUDIO_HASHIRAMA_2_z5sxss`,
      `${BASE_IMAGE_URL}/JLSTUDIO_HASHIRAMA_3_xt7qj0`,
    ],
  },
  {
    id: 'JLSTUDIO_KISAME',
    name: 'Hoshigaki Kisame',
    series: 'Akatsuki',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_700_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_KISAME_1_hxp4nd`,
      `${BASE_IMAGE_URL}/JLSTUDIO_KISAME_2_dhsmvm`,
      `${BASE_IMAGE_URL}/JLSTUDIO_KISAME_3_b9r7vl`,
    ],
  },
  {
    id: 'JLSTUDIO_SIXPATHSSAGE_NARUTO',
    name: 'Uzumaki Naruto',
    series: 'Six Paths Sage',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_700_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_SIXPATHSSAGE_NARUTO_1_qfl5im`,
      `${BASE_IMAGE_URL}/JLSTUDIO_SIXPATHSSAGE_NARUTO_2_ui6ybi`,
    ],
  },
  {
    id: 'JLSTUDIO_SIXPATHSRINNEGAN_SASUKE',
    name: 'Uchiha Sasuke',
    series: 'Six Paths Rinnegan',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_700_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_SIXPATHSRINNEGAN_SASUKE_1_lk168q`,
      `${BASE_IMAGE_URL}/JLSTUDIO_SIXPATHSRINNEGAN_SASUKE_2_im9nei`,
    ],
  },
  {
    id: 'ZSTUDIO_JK001_GOJO',
    name: 'Gojo Satoru',
    series: '',
    studio: 'Z Studio',
    material: 'Resin',
    type: 'Jujutsu Kaisen',
    price: 1_300_000,
    images: [
      `${BASE_IMAGE_URL}/ZSTUDIO_JK001_GOJO_1_j1aba1`,
      `${BASE_IMAGE_URL}/ZSTUDIO_JK001_GOJO_2_nvwemg`,
    ],
  },
  {
    id: 'ZSTUDIO_JK002_SUKUNA',
    name: 'Ryomen Sukuna',
    series: '',
    studio: 'Z Studio',
    material: 'Resin',
    type: 'Jujutsu Kaisen',
    price: 1_250_000,
    images: [
      `${BASE_IMAGE_URL}/ZSTUDIO_JK002_SUKUNA_1_rvsexw`,
      `${BASE_IMAGE_URL}/ZSTUDIO_JK002_SUKUNA_2_jencfo`,
    ],
  },
  {
    id: 'ZSTUDIO_JK003_MAHORAGA',
    name: 'Mahoraga',
    series: '',
    studio: 'Z Studio',
    material: 'Resin',
    type: 'Jujutsu Kaisen',
    price: 1_850_000,
    images: [
      `${BASE_IMAGE_URL}/ZSTUDIO_JK003_MAHORAGA_1_k7kmob`,
      `${BASE_IMAGE_URL}/ZSTUDIO_JK003_MAHORAGA_2_w8lch7`,
    ],
  },
  {
    id: 'ZSTUDIO_JK004_HIGURUMA',
    name: 'Higuruma Hiromi',
    series: '',
    studio: 'Z Studio',
    material: 'Resin',
    type: 'Jujutsu Kaisen',
    price: 2_750_000,
    images: [
      `${BASE_IMAGE_URL}/ZSTUDIO_JK004_HIGURUMA_1_pmbfu8`,
      `${BASE_IMAGE_URL}/ZSTUDIO_JK004_HIGURUMA_2_xdqcs8`,
      `${BASE_IMAGE_URL}/ZSTUDIO_JK004_HIGURUMA_3_yitiuz`,
    ],
  },
  {
    id: 'ZSTUDIO_JK005_SUKUNA',
    name: 'Ryomen Sukuna',
    series: '',
    studio: 'Z Studio',
    material: 'Resin',
    type: 'Jujutsu Kaisen',
    price: 1_700_000,
    images: [
      `${BASE_IMAGE_URL}/ZSTUDIO_JK005_SUKUNA_1_pievku`,
      `${BASE_IMAGE_URL}/ZSTUDIO_JK005_SUKUNA_2_nvbnlh`,
    ],
  },
  {
    id: 'ZSTUDIO_JK006_TENGEN',
    name: 'Tengen',
    series: '',
    studio: 'Z Studio',
    material: 'Resin',
    type: 'Jujutsu Kaisen',
    price: 1_250_000,
    images: [
      `${BASE_IMAGE_URL}/ZSTUDIO_JK006_TENGEN_1_tkzrcd`,
      `${BASE_IMAGE_URL}/ZSTUDIO_JK006_TENGEN_2_zcpxgc`,
    ],
  },
  {
    id: 'ZSTUDIO_JK007_TOJI',
    name: 'Fushiguro Toji',
    series: '',
    studio: 'Z Studio',
    material: 'Resin',
    type: 'Jujutsu Kaisen',
    price: 1_500_000,
    images: [
      `${BASE_IMAGE_URL}/ZSTUDIO_JK007_TOJI_1_pyt46l`,
      `${BASE_IMAGE_URL}/ZSTUDIO_JK007_TOJI_2_yukyxl`,
    ],
  },
  {
    id: 'ZSTUDIO_JK008_TSUKUMO',
    name: 'Tsukumo Yuki',
    series: '',
    studio: 'Z Studio',
    material: 'Resin',
    type: 'Jujutsu Kaisen',
    price: 1_450_000,
    images: [`${BASE_IMAGE_URL}/ZSTUDIO_JK008_TSUKUMO_1_tzyhcc`],
  },
  {
    id: 'ZSTUDIO_JK009_TOJI',
    name: 'Fushiguro Toji',
    series: '',
    studio: 'Z Studio',
    material: 'Resin',
    type: 'Jujutsu Kaisen',
    price: 1_350_000,
    images: [
      `${BASE_IMAGE_URL}/ZSTUDIO_JK009_TOJI_1_yljlio`,
      `${BASE_IMAGE_URL}/ZSTUDIO_JK009_TOJI_2_mmbmf9`,
      `${BASE_IMAGE_URL}/ZSTUDIO_JK009_TOJI_3_pfaa2f`,
    ],
  },
  {
    id: 'ZSTUDIO_JK010_ITADORI',
    name: 'Itadori Yuji',
    series: '',
    studio: 'Z Studio',
    material: 'Resin',
    type: 'Jujutsu Kaisen',
    price: 1_300_000,
    images: [`${BASE_IMAGE_URL}/ZSTUDIO_JK010_ITADORI_1_mzivd0`],
  },
];
