export const BASE_IMAGE_URL = 'https://res.cloudinary.com/dahbzn13g/image/upload';
export const PRODUCTS = [
  {
    id: 'G5STUDIOHASHIRAMASENJU',
    name: 'Senju Hashirama',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 9_000_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHASHIRAMASENJU_2_dxgtps.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHASHIRAMASENJU_1_flw2wn.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHASHIRAMASENJU_4_qqqy6t.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHASHIRAMASENJU_3_merjm4.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHASHIRAMASENJU_5_gss1p5.webp`,
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESMADARAUCHIHA',
    name: 'Uchiha Madara',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 9_300_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESMADARAUCHIHA_2_ga1nlj.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESMADARAUCHIHA_1_kp1yef.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESMADARAUCHIHA_3_sq0ogf.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESMADARAUCHIHA_4_tr6j8o.webp`,
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIES',
    name: 'Namikaze Minato',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 8_400_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIES_3_z9a1n7.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIES_1_pxzr9g.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIES_4_oiezah.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIES_5_ni1v5s.webp`,
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA',
    name: 'Uchiha Obito',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 9_000_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA_2_c6xclg.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA_1_qtiinu.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA_3_dl5pny.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA_4_y8pxsd.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESOBITOUCHIHA_6_ci2lfd.webp`,
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESITACHIUCHIHA',
    name: 'Uchiha Itachi',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 9_700_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESITACHIUCHIHA_2_fyamvf.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESITACHIUCHIHA_1_vctoqz.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESITACHIUCHIHA_3_vicorm.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESITACHIUCHIHA_4_gybzbs.webp`,
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESSASUKEUCHIHA',
    name: 'Uchiha Sasuke',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 9_300_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESSASUKEUCHIHA_2_hwrksy.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESSASUKEUCHIHA_1_ddw18o.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESSASUKEUCHIHA_3_bbdryr.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESSASUKEUCHIHA_4_pc94pz.webp`,
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA',
    name: 'Jiraiya',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 8_200_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA_2_dnheee.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA_1_z2lxw3.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA_3_aniyud.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA_4_kvfnm2.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESJIRAIYA_5_k6xiks.webp`,
    ],
  },
  {
    id: 'G5STUDIOSIXPATHSOFPAIN',
    name: 'Six Paths Of Pain',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 14_850_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSIXPATHSOFPAIN_1_ftwje2.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSIXPATHSOFPAIN_2_wuglfx.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSIXPATHSOFPAIN_3_mcnbbh.webp`,
    ],
  },
  {
    id: 'G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI',
    name: 'Uzumaki Naruto',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 18_650_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_2_tu5kbk.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_1_fp0qrq.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_4_wgdzvp.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_7_bb5wiz.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_6_ze4ci6.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_3_cipuug.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGHENDCUSTOMSERIESTHELIFEOFNARUTOUZUMAKI_5_yprcsb.webp`,
    ],
  },
  {
    id: 'G5STUDIOHIGH-ENDCUSTOMSERIESGAARA',
    name: 'Gaara',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_300_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESGAARA_2_axwfzg.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESGAARA_1_wuj6gd.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESGAARA_5_m2m1ix.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESGAARA_3_dhpmki.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOHIGH-ENDCUSTOMSERIESGAARA_6_mtgeby.webp`,
    ],
  },
  {
    id: 'G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA',
    name: 'Deidara',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 5_000_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA_2_njxnso.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA_1_qm7kmn.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA_3_ac0t19.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA_5_d87nqm.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_DEIDARA_4_bowwmo.webp`,
    ],
  },
  {
    id: 'G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY',
    name: 'Might Guy',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 4_700_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY_3_m5sh01.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY_1_dlylzt.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY_4_rllku4.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY_2_ftr3aq.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_EIGHTHGATENIGHTGUY_5_ypma5y.webp`,
    ],
  },
  {
    id: 'G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI',
    name: 'Hoshigaki Kisame',
    series: 'Advance',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 5_100_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI_2_kv7rws.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI_1_pwzmmu.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI_3_mrqiqi.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI_4_wmmysi.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_NARUTOHIGH-ENDCUSTOMSERIES_KISAMEHOSHIGAKI_5_tvgufm.webp`,
    ],
  },
  {
    id: 'G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY',
    name: 'Monkey D. Luffy',
    series: 'Four Emperors Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_000_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_7_jfergr.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_1_chjdnv.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_6_mhh8ob.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_2_bf6iti.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_8_zfxxvy.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_3_nn5czs.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOFOUREMPERORSERIESMONKEYDLUFFY_5_jykp1n.webp`,
    ],
  },
  {
    id: 'G5STUDIOONEPIECETHEROADTOBEKING',
    name: 'Monkey D. Luffy',
    series: 'The Road To Be King',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 28_300_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_10_wdq6my.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_9_qs0kmp.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_8_faltis.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_3_yqmkly.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_7_t7dbyw.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_2_zdcxcx.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_6_ttkudp.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_5_vqdlnb.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOONEPIECETHEROADTOBEKING_4_yfmvb3.webp`,
    ],
  },
  {
    id: 'G5STUDIOONEPIECEENMAFORMRORONOAZORO',
    name: 'Roronoa Zoro',
    series: 'Enma Form',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_300_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_5_y3jy9u.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_1_s3vcwm.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_4_agwrkz.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_3_ws0pp9.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_ONEPIECEENMAFORMRORONOAZORO_2_kjabt9.webp`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESLUFFY',
    name: 'Monkey D. Luffy',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 6_300_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESLUFFY_1_gyyxbk.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESLUFFY_6_ul1b70.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESLUFFY_3_ovbeyi.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESLUFFY_2_foyzua.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESLUFFY_4_rmhx1k.webp`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESZORO',
    name: 'Roronoa Zoro',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESZORO_1_sfbppo.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESZORO_7_xzafyc.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESZORO_3_ut02ud.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESZORO_4_mt1u4a.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESZORO_2_jcsc3h.webp`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESNAMI',
    name: 'Nami',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESSERIESNAMI_1_a0o0l8.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESSERIESNAMI_2_dc1la1.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESSERIESNAMI_4_zsscpc.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESSERIESNAMI_3_fwmkxp.webp`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESUSOPP',
    name: 'Usopp',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESSERIESUSOPP_1_zdfmeg.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESSERIESUSOPP_2_xhub5g.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESSERIESUSOPP_4_wwzssy.webp`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESSANJI',
    name: 'Vinsmoke Sanji',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESSANJI_1_bwouuo.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESSANJI_5_h5fzpi.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESSANJI_2_s2yeya.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESSANJI_3_ilyd3c.webp`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESSERIESCHOPPER',
    name: 'Tony Tony Chopper',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_1_ss1ydb.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_3_jdqdbq.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_2_nrtsby.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESCHOPPER_5_wwkwf9.webp`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESROBIN',
    name: 'Nico Robin',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 6_300_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESROBIN_1_kisc1x.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESROBIN_2_rjad8j.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESROBIN_4_yw59uy.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESROBIN_3_pn9dez.webp`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESFRANKY',
    name: 'Franky',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 6_100_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESFRANKY_1_ncnmtz.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESFRANKY_6_y2epwn.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESFRANKY_2_bq46jp.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESFRANKY_3_f4kcx2.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESFRANKY_4_csip0h.webp`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESBROOK',
    name: 'Brook',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 5_700_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESBROOK_1_tz5gyd.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESBROOK_3_waeebd.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESBROOK_5_ce3n3p.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESBROOK_6_fahluw.webp`,
    ],
  },
  {
    id: 'G5STUDIOSTRAWHATPIRATESERIESJINBE',
    name: 'Jinbe',
    series: 'Straw Hat Pirates Series',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESJINBE_1_d8ixa3.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESJINBE_1_gv6jwe.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESJINBE_3_ahmdwc.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOSTRAWHATPIRATESERIESJINBE_2_j68zg0.webp`,
    ],
  },
  {
    id: 'G5STUDIOYAMATO',
    name: 'Yamato',
    series: '',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_900_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOYAMATO_1_xbejip.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOYAMATO_2_syorwi.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOYAMATO_3_ghokw3.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOYAMATO_4_lvphta.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOYAMATO_5_nzoism.webp`,
    ],
  },
  {
    id: 'G5STUDIO_RENGOKU',
    name: 'Kyojuro Rengoku',
    series: 'Flame Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 3_100_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_RENGOKU_2_eer0ir.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_RENGOKU_1_qo9a4t.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_RENGOKU_3_ogfnto.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_RENGOKU_4_rthy71.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_RENGOKU_5_oszvxs.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_RENGOKU_6_bvzphr.jpg`,
    ],
  },
  {
    id: 'G5STUDIO_ZENITSU',
    name: 'Agatsuma Zenitsu',
    series: 'Thunder Breathing',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_800_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_2_fom7f1.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_3_d859sn.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_1_zkmhwq.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_4_dy6qu8.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_5_mrbxsb.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_6_d0nzge.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_7_dnyl1c.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_8_fgexv6.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_ZENITSU_9_wakjcj.jpg`,
    ],
  },
  {
    id: 'G5STUDIO_GIYU',
    name: 'Tomioka Giyu',
    series: 'Water Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_800_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_GIYU_5_zknov6.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_GIYU_1_hutf4d.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_GIYU_2_ssomqo.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_GIYU_4_lh6eju.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_GIYU_3_ngeoox.jpg`,
    ],
  },
  {
    id: 'G5STUDIO_MITSURI',
    name: 'Kanroji Mitsuri',
    series: 'Love Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_850_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_MITSURI_2_vlas5h.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_MITSURI_1_wayac5.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_MITSURI_3_c5vbrh.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_MITSURI_4_sikzuc.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_MITSURI_5_xu4hiv.jpg`,
    ],
  },
  {
    id: 'G5STUDIO_SANEMI',
    name: 'Shinazugawa Sanemi',
    series: 'Wind Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_800_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_SANEMI_1_wf9a8s.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_SANEMI_2_r8oysh.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_SANEMI_3_codgfv.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_SANEMI_4_lqxwiy.jpg`,
    ],
  },
  {
    id: 'G5STUDIO_MUZAN',
    name: 'Kibutsuji Muzan',
    series: 'Demon King',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_800_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_MUZAN_2_yugz1s.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_MUZAN_1_vjtx4f.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_MUZAN_5_gjexbv.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_MUZAN_3_kmomuz.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_MUZAN_4_h5jna5.jpg`,
    ],
  },
  {
    id: 'G5STUDIO_GYOMEI',
    name: 'Himejima Gyomei',
    series: 'Stone Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_800_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_GYOMEI_2_qb0hnj.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_GYOMEI_1_qkdiyr.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_GYOMEI_3_egt8ws.jpg`,
    ],
  },
  {
    id: 'WATERBREATHINGTANJIRO',
    name: 'Kamado Tanjiro',
    series: 'Water Breathing',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 4_400_000,
    images: [
      `${BASE_IMAGE_URL}/WATERBREATHINGTANJIRO_2_il2iwd.webp`,
      `${BASE_IMAGE_URL}/WATERBREATHINGTANJIRO_4_idbyaz.webp`,
      `${BASE_IMAGE_URL}/WATERBREATHINGTANJIRO_5_ch3xqm.webp`,
      `${BASE_IMAGE_URL}/WATERBREATHINGTANJIRO_3_zdreu7.webp`,
    ],
  },
  {
    id: 'G5STUDIO_DEMONSLAYERFLAMEBREATHINGKYOJURORENGOKU',
    name: 'Kyojuro Rengoku',
    series: 'Flame Breathing',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 5_200_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_DEMONSLAYERFLAMEBREATHINGKYOJURORENGOKU_4_nhlbeb.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_DEMONSLAYERFLAMEBREATHINGKYOJURORENGOKU_3_g4qvzc.webp`,
      `${BASE_IMAGE_URL}/G5STUDIO_DEMONSLAYERFLAMEBREATHINGKYOJURORENGOKU_1_v6gfxe.webp`,
    ],
  },
  {
    id: 'G5STUDIO_AKAZA',
    name: 'Akaza',
    series: 'Upper Moon 3',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 3_100_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_AKAZA_1_ubpmac.avif`,
      `${BASE_IMAGE_URL}/G5STUDIO_AKAZA_2_xynimx.avif`,
      `${BASE_IMAGE_URL}/G5STUDIO_AKAZA_3_ddpsia.avif`,
    ],
  },
  {
    id: 'G5STUDIO_OBANAI',
    name: 'Iguro Obanai',
    series: 'Serpent Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_350_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_OBANAI_2_bjclyq.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_OBANAI_1_jpnd6m.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_OBANAI_3_brbhgm.jpg`,
    ],
  },
  {
    id: 'G5STUDIO_TENGEN',
    name: 'Uzui Tengen',
    series: 'Sound Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_850_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_TENGEN_2_pz8q2j.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_TENGEN_1_gvi0sn.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_TENGEN_3_jrek5l.jpg`,
    ],
  },
  {
    id: 'G5STUDIO_SHINOBU',
    name: 'Kocho Shinobu',
    series: 'Insect Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_350_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_SHINOBU_2_aisny3.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_SHINOBU_1_f6jbxa.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_SHINOBU_3_vznhub.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_SHINOBU_4_bxnfta.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_SHINOBU_5_jnbai8.jpg`,
    ],
  },
  {
    id: 'G5STUDIO_MUICHIRO',
    name: 'Tokito Muichiro',
    series: 'Mist Pillar',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 3_700_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_MUICHIRO_2_imalot.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_MUICHIRO_1_arwqm9.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_MUICHIRO_3_cw18mz.jpg`,
    ],
  },
  {
    id: 'G5STUDIO_YORIICHI_2',
    name: 'Tsugikuni Yoriichi',
    series: 'Sun Breathing',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 2_300_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIO_YORIICHI_3_tdiwzx.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_YORIICHI_1_rlvchd.jpg`,
      `${BASE_IMAGE_URL}/G5STUDIO_YORIICHI_2_wfeerp.jpg`,
    ],
  },
  {
    id: 'G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO',
    name: 'Kamado Tanjiro',
    series: 'Sun Breathing',
    studio: 'G5 Studio',
    material: 'Resin',
    type: 'Demon Slayer',
    price: 4_050_000,
    images: [
      `${BASE_IMAGE_URL}/G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO_2_atpl6f.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO_1_i3cs9e.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO_4_v9gizn.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO_3_bjjyzj.webp`,
      `${BASE_IMAGE_URL}/G5STUDIOINFINITYCASTLEARCSUNBREATHINGTANJIRO_5_iq8ijp.webp`,
    ],
  },
  {
    id: 'TOYSTUDIOSAWADATSUNAYOSHI',
    name: 'Sawada Tsunayoshi',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_300_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIOSAWADATSUNAYOSHI_xbx2ds.jpg`],
  },
  {
    id: 'TOYSTUDIOGOKUDERA',
    name: 'Hayato Gokudera',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_250_000,
    images: [
      `${BASE_IMAGE_URL}/TOYSTUDIOGOKUDERA_1_hg7mub.jpg`,
      `${BASE_IMAGE_URL}/TOYSTUDIOGOKUDERA_2_hd5y8r.jpg`,
    ],
  },
  {
    id: 'TOYSTUDIOROKUDOUMUKURO',
    name: 'Rokudo Mukuro',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_300_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIOROKUDOUMUKURO_i81gtn.jpg`],
  },
  {
    id: 'TOYSTUDIOHIBARIKYOYA',
    name: 'Kyoya Hibari',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_250_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIOHIBARIKYOYA_iuiyjh.jpg`],
  },
  {
    id: 'TOYSTUDIORANBO1',
    name: 'Lambo',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_250_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIORANBO_1_nbpyxg.jpg`],
  },
  {
    id: 'TOYSTUDIOKUROMU',
    name: 'Chrome Dokuro',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_250_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIOKUROMU_adalm7.jpg`],
  },
  {
    id: 'TOYSTUDIOYAMAMOTO',
    name: 'Takeshi Yamamoto',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_300_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIOYAMAMOTO_vyf0jo.jpg`],
  },
  {
    id: 'TOYSTUDIOSASAGAWA',
    name: 'Sasagawa Ryohei',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_700_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIOSASAGAWA_hy6o7s.jpg`],
  },
  {
    id: 'TOYSTUDIORANBO2',
    name: 'Lambo',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_700_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIORANBO_2_asy5ic.jpg`],
  },
  {
    id: 'TOYSTUDIOGIOTTO',
    name: 'Giotto (Sawada Ieyasu)',
    series: 'Katekyo Hitman Reborn',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Katekyo Hitman Reborn',
    price: 1_600_000,
    images: [`${BASE_IMAGE_URL}/TOYSTUDIOGIOTTO_igivkd.jpg`],
  },
  {
    id: 'TOYSTUDIO_NATSU',
    name: 'Natsu',
    series: 'Fairy Tail',
    studio: 'TOY Studio',
    material: 'Resin',
    type: 'Fairy Tail',
    price: 2_400_000,
    images: [
      `${BASE_IMAGE_URL}/TOYSTUDIO_NATSU_1_cvfu65.webp`,
      `${BASE_IMAGE_URL}/TOYSTUDIO_NATSU_2_fr0pvh.webp`,
    ],
  },
  {
    id: 'YZSTUDIO_EXPLUS_EUSTASSKID',
    name: 'Eustass Kid',
    series: 'Ex Plus Magnet Demon',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 3_000_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_EUSTASSKID_1_psqbpr.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_EUSTASSKID_2_vlpkot.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_EUSTASSKID_3_f3mybv.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_EUSTASSKID_4_rzftey.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_EUSTASSKID_5_tjleui.jpg`,
    ],
  },
  {
    id: 'YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA',
    name: 'Bartholomew Kuma',
    series: 'Ex Plus',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 1_900_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_1_b4gq5i.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_2_wyf7ae.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_3_r3uyo2.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_4_ovnnvg.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_5_ub5sfv.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_BARTHOLOMEWKUMA_6_a984av.jpg`,
    ],
  },
  {
    id: 'YZSTUDIO_EXPLUS_RORONOAZORO',
    name: 'Roronoa Zoro',
    series: 'Ex Plus Flying Dragon Fire Blaze',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_600_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_RORONOAZORO_1_ybjirm.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_RORONOAZORO_2_crhptc.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_RORONOAZORO_3_nzudqq.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_RORONOAZORO_4_hkyj9i.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_RORONOAZORO_5_y6dsjb.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_RORONOAZORO_6_qrkp9r.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_RORONOAZORO_7_rfx0z6.jpg`,
    ],
  },
  {
    id: 'YZSTUDIO_EXPLUS_KING',
    name: 'King',
    series: 'Ex Plus Omori Karyudon',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_300_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_KING_1_iorz3x.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_KING_2_axx57m.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_KING_3_x0n0g4.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_KING_4_nqm6p1.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_KING_5_pazxml.jpg`,
    ],
  },
  {
    id: 'YZSTUDIO_EXPLUS_VINSMOKESANJI',
    name: 'Vinsmoke Sanji',
    series: 'Ex Plus Goodbye Germa Blue Fire',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_700_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_1_ahpkqm.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_2_lca1tc.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_3_rhmgyq.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_4_brop6d.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_5_mfo9gs.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_6_dqpljd.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_7_favzsu.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EXPLUS_VINSMOKESANJI_8_l6db3r.jpg`,
    ],
  },
  {
    id: 'YZSTUDIO_EC001_TOSHIRO',
    name: 'Hitsugaya Toshiro: Daiguren Hyorinmaru',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_000_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC001_TOSHIRO_1_swkk4p.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC001_TOSHIRO_2_vofen1.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC001_TOSHIRO_3_n1blrs.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC001_TOSHIRO_4_izy9is.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC001_TOSHIRO_5_uwa4aj.jpg`,
    ],
  },
  {
    id: 'YZSTUDIO_EC002_AIZEN',
    name: 'Aizen Sokuke: Goryutenmetsu',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_200_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC002_AIZEN_1_tt88kt.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC002_AIZEN_2_havpmp.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC002_AIZEN_3_oj0fxw.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC002_AIZEN_4_x1giaj.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC002_AIZEN_5_zrprp7.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC002_AIZEN_6_lnow6z.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC002_AIZEN_7_egrmdy.jpg`,
    ],
  },
  {
    id: 'YZSTUDIO_EC003_BYAKUYA',
    name: 'Kuchiki Byakuya: Senbonzakura Kageyoshi',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_200_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC003_BYAKUYA_1_kgc3ib.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC003_BYAKUYA_2_g5crgz.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC003_BYAKUYA_3_vpl3cb.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC003_BYAKUYA_4_nasgor.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC003_BYAKUYA_5_cjgff2.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC003_BYAKUYA_6_zio1rc.jpg`,
    ],
  },
  {
    id: 'YZSTUDIO_EC004_SHUNSUI',
    name: 'Kyoraku Shunsui: Katen Kyokotsu Karamatsu Shinju',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_200_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC004_SHUNSUI_1_uvglyp.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC004_SHUNSUI_2_nn2eck.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC004_SHUNSUI_3_n9tpwf.jpg`,
    ],
  },
  {
    id: 'YZSTUDIO_EC005_RETSU',
    name: 'Unohana Retsu: Minazuki',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_250_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC005_RETSU_1_nb9arw.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC005_RETSU_2_clgkhn.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC005_RETSU_3_nrjwnf.jpg`,
    ],
  },
  {
    id: 'YZSTUDIO_EC006_MAYURI',
    name: 'Kurotsuchi Mayuri: Konjiki Ashisogi Jizo Matai Fukuin Shotai',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 7_000_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC006_MAYURI_1_fxriaj.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC006_MAYURI_2_tx1bka.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC006_MAYURI_3_uileg6.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC006_MAYURI_4_uankil.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC006_MAYURI_5_w63wie.jpg`,
    ],
  },
  {
    id: 'YZSTUDIO_EC007_YAMAMOTO',
    name: 'Yamamoto Genryusai Shigekuni: Zanka No Tachi',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 1_950_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC007_YAMAMOTO_1_fi1niz.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC007_YAMAMOTO_2_les4n9.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC007_YAMAMOTO_3_plmxby.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC007_YAMAMOTO_4_oj7roa.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC007_YAMAMOTO_5_nfws0b.jpg`,
    ],
  },
  {
    id: 'YZSTUDIO_EC008_SHINJI',
    name: 'Hirako Shinji: Sakashima Yokoshima Happofusagari',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_750_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC008_SHINJI_1_dezggv.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC008_SHINJI_2_yeg2i5.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC008_SHINJI_3_dwqvtz.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC008_SHINJI_4_bs5tqf.jpg`,
    ],
  },
  {
    id: 'YZSTUDIO_EC009_URAHARA',
    name: 'Urahara Kisuke: Kannonbiraki Benihime Aratame',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 3_000_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC009_URAHARA_1_xjbiwh.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC009_URAHARA_2_a1kccd.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC009_URAHARA_3_ff3jog.jpg`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC009_URAHARA_4_qmncxf.jpg`,
    ],
  },
  {
    id: 'YZSTUDIO_EC010_GRIMMJOW',
    name: 'Grimmjow Jaegerjaquez: Pantera Resurreccion',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 1_700_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_1_kinnpp.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_2_wap10z.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_3_fkys1d.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_4_nsq9et.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_5_knmvix.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_6_rze9ay.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_7_ogfdlv.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_8_eadhiw.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC010_GRIMMJOW_9_yfgmrj.webp`,
    ],
  },
  {
    id: 'YZSTUDIO_EC011_YHWACH',
    name: 'Yhwach: Soul King',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 3_750_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC011_YHWACH_1_wlrdea.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC011_YHWACH_2_iw9rtv.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC011_YHWACH_3_j3obhv.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC011_YHWACH_4_lch4bf.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC011_YHWACH_5_rkg88l.webp`,
    ],
  },
  {
    id: 'YZSTUDIO_EC014_KENPACHI',
    name: 'Zaraki Kenpachi',
    series: 'Effect Collection',
    studio: 'YZ Studio',
    material: 'Resin',
    type: 'Bleach',
    price: 2_850_000,
    images: [
      `${BASE_IMAGE_URL}/YZSTUDIO_EC014_KENPACHI_1_odze0n.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC014_KENPACHI_2_hyfhcp.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC014_KENPACHI_4_mlthvz.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC014_KENPACHI_6_wfg989.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC014_KENPACHI_3_gnezfl.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC014_KENPACHI_5_qkftom.webp`,
      `${BASE_IMAGE_URL}/YZSTUDIO_EC014_KENPACHI_7_kbzqum.webp`,
    ],
  },
  {
    id: 'APLUSSTUDIO_SAKAZUKI',
    name: 'Sakazuki (Akainu)',
    series: 'Navy Admiral',
    studio: 'A+ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_400_000,
    images: [
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_SAKAZUKI_1_cxbtpy.jpg`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_SAKAZUKI_2_oiimjj.jpg`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_SAKAZUKI_3_o6wzgj.jpg`,
    ],
  },
  {
    id: 'APLUSSTUDIO_KUZAN',
    name: 'Kuzan (Aokiji)',
    series: 'Navy Admiral',
    studio: 'A+ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_450_000,
    images: [
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_KUZAN_1_ealqhj.jpg`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_KUZAN_2_jfza2d.jpg`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_KUZAN_3_niqib7.jpg`,
    ],
  },
  {
    id: 'APLUSSTUDIO_BORSALINO',
    name: 'Borsalino (Kizaru)',
    series: 'Navy Admiral',
    studio: 'A+ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_600_000,
    images: [
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_BORSALINO_1_r1vmrv.jpg`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_BORSALINO_2_ohfi4z.jpg`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_BORSALINO_3_jzheci.jpg`,
    ],
  },
  {
    id: 'APLUSSTUDIO_ISSHO',
    name: 'Issho (Fujitora)',
    series: 'Navy Admiral',
    studio: 'A+ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_650_000,
    images: [
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_ISSHO_1_zvxcfi.jpg`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_ISSHO_2_vx4fih.jpg`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_ISSHO_3_yr4hvt.jpg`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_ISSHO_4_wis7lw.jpg`,
    ],
  },
  {
    id: 'APLUSSTUDIO_ARAMAKI',
    name: 'Aramaki (Ryokugyu)',
    series: 'Navy Admiral',
    studio: 'A+ Studio',
    material: 'Resin',
    type: 'One Piece',
    price: 2_700_000,
    images: [
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_ARAMAKI_1_j7bir4.jpg`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_ARAMAKI_2_hgjwfy.jpg`,
      `${BASE_IMAGE_URL}/v1785567187/APLUSSTUDIO_ARAMAKI_3_ukhjhv.jpg`,
    ],
  },
  {
    id: 'JLSTUDIO_KAKASHI',
    name: 'Hatake Kakashi',
    series: '',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_500_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_KAKASHI_1_ez1war.jpg`,
      `${BASE_IMAGE_URL}/JLSTUDIO_KAKASHI_2_ybkwoq.jpg`,
      `${BASE_IMAGE_URL}/JLSTUDIO_KAKASHI_3_giztgg.jpg`,
    ],
  },
  {
    id: 'JLSTUDIO_OBITO',
    name: 'Uchiha Obito',
    series: '',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_600_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_OBITO_1_uadhd1.webp`,
      `${BASE_IMAGE_URL}/JLSTUDIO_OBITO_2_vwavls.webp`,
      `${BASE_IMAGE_URL}/JLSTUDIO_OBITO_3_eyh9mx.webp`,
    ],
  },
  {
    id: 'JLSTUDIO_GUY',
    name: 'Might Guy',
    series: '',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_600_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_GUY_1_curqnh.avif`,
      `${BASE_IMAGE_URL}/JLSTUDIO_GUY_2_psgdmk.avif`,
    ],
  },
  {
    id: 'JLSTUDIO_MADARA',
    name: 'Uchiha Madara',
    series: '',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_650_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_MADARA_1_kkwwg7.jpg`,
      `${BASE_IMAGE_URL}/JLSTUDIO_MADARA_2_whzzbn.jpg`,
      `${BASE_IMAGE_URL}/JLSTUDIO_MADARA_3_teo0ig.jpg`,
    ],
  },
  {
    id: 'JLSTUDIO_ITACHI',
    name: 'Uchiha Itachi',
    series: 'Akatsuki',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_650_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_ITACHI_1_mvtudm.jpg`,
      `${BASE_IMAGE_URL}/JLSTUDIO_ITACHI_2_ceuypl.jpg`,
    ],
  },
  {
    id: 'JLSTUDIO_SASORI',
    name: 'Sasori',
    series: 'Akatsuki',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_650_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_SASORI_1_daztve.jpg`,
      `${BASE_IMAGE_URL}/JLSTUDIO_SASORI_2_mged0k.jpg`,
    ],
  },
  {
    id: 'JLSTUDIO_HASHIRAMA',
    name: 'Senju Hashirama',
    series: '',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_700_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_HASHIRAMA_1_eal5jd.jpg`,
      `${BASE_IMAGE_URL}/JLSTUDIO_HASHIRAMA_2_z5sxss.jpg`,
      `${BASE_IMAGE_URL}/JLSTUDIO_HASHIRAMA_3_xt7qj0.jpg`,
    ],
  },
  {
    id: 'JLSTUDIO_KISAME',
    name: 'Hoshigaki Kisame',
    series: 'Akatsuki',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_700_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_KISAME_1_hxp4nd.jpg`,
      `${BASE_IMAGE_URL}/JLSTUDIO_KISAME_2_dhsmvm.jpg`,
      `${BASE_IMAGE_URL}/JLSTUDIO_KISAME_3_b9r7vl.jpg`,
    ],
  },
  {
    id: 'JLSTUDIO_SIXPATHSSAGE_NARUTO',
    name: 'Uzumaki Naruto',
    series: 'Six Paths Sage',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_700_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_SIXPATHSSAGE_NARUTO_1_qfl5im.jpg`,
      `${BASE_IMAGE_URL}/JLSTUDIO_SIXPATHSSAGE_NARUTO_2_ui6ybi.jpg`,
    ],
  },
  {
    id: 'JLSTUDIO_SIXPATHSRINNEGAN_SASUKE',
    name: 'Uchiha Sasuke',
    series: 'Six Paths Rinnegan',
    studio: 'JL Studio',
    material: 'Resin',
    type: 'Naruto',
    price: 1_700_000,
    images: [
      `${BASE_IMAGE_URL}/JLSTUDIO_SIXPATHSRINNEGAN_SASUKE_1_lk168q`,
      `${BASE_IMAGE_URL}/JLSTUDIO_SIXPATHSRINNEGAN_SASUKE_2_im9nei`,
    ],
  },
];
